### ISSUE TITLE
Pandoc required to build docs

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-ml#106]
I was trying to build the `dask-ml` documentation locally and got the following output from `make html` 

```
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 45 source files that are out of date
updating environment: 45 added, 0 changed, 0 removed
reading sources... [ 11%] examples/dask-glm                                                                                                                                   
Notebook error:
PandocMissing in examples/dask-glm.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
http://pandoc.org/installing.html
make: *** [html] Error 1
```

It looks like Pandoc is missing  from my dev environment (created using `conda env create -f ci/environment.yml --name=dask-ml_dev`). After manually installing Pandoc from `conda-forge`, I was able to build the documentation successfully. 

Not sure if I missed something when setting up my environment. If not, I'd be happy to submit a PR adding Pandoc to `ci/environment.yml` and `ci/environment-27.yml`

**Comment by TomAugspurger** [comment]
Hmm yes I forgot about that dependency, sorry about that.

Let's hold off on adding it for now. I'm trying out sphinx-gallery in https://github.com/dask/dask-ml/pull/91, and it seems to work pretty well (it also produces a downloadable Jupyter notebook).

**Comment by jrbourbeau** [comment]
Alright, sounds good. Thanks @TomAugspurger

**Comment by jrbourbeau** [comment]
The documentation can be built with the new `sphinx-gallery` dependency in `ci/environment.yml`. Closing this issue.
