### ISSUE TITLE
How does dask-ml handle large datasets?

### ISSUE THREAD

**Issue by rhiever** [dask/dask-ml#109]
From the latest demos of dask-sklearn (and related projects) that I've seen, dask has primarily focused on parallelizing grid/random search and CV, and provides some smart caching mechanisms for transformers and estimators that have already been evaluated on a dataset.

However, that approach breaks down when, say, a slow algorithm is being trained on a very large dataset. With some slower algorithms, training one instance of the algorithm on one fold of the dataset can take hours or days, which makes training the algorithm unviable for all but the most patient practitioner.

Can dask-ml speed up the underlying ML algorithms that it supports?

**Comment by mrocklin** [comment]
Several of the algorithms mentioned in the documentation are parallel implementations on large datasets.  See http://dask-ml.readthedocs.io/en/latest/

**Comment by rhiever** [comment]
Can we please explicitly list them here? Are the GLMs a custom implementation in dask? Future plans?

**Comment by mrocklin** [comment]
> Can we please explicitly list them here?

I'm not sure I undestand the question.  They are all listed in the documentation.  Perhaps you want the API reference? http://dask-ml.readthedocs.io/en/latest/modules/api.html

If you want to list them here that would be fine with me.

> Are the GLMs a custom implementation in dask?

Yes. This is already answered in the documentation.  See http://dask-ml.readthedocs.io/en/latest/glm.html

If the documentation is not sufficiently clear it would be great if you would collaborate to improve it.

**Comment by rhiever** [comment]
Sorry, I was typing quickly to finish my thoughts before a call and didn't do a good job. I think I'm asking a question that wouldn't necessarily be expected to be covered by the docs.

What I meant was: What are all the custom algorithm implementations from scratch in dask-ml? I picked up from the docs that GLMs are indeed a custom implementation from scratch. Others (?):

* Preprocessors
* Spectral clustering

The rest seem to wrap existing implementations in some way to better parallelize them, e.g., for parameter search or CV. Is that a correct characterization?

**Comment by mrocklin** [comment]
It seems like a brief page describing the scalability of different approaches might be in-scope.

**Comment by marcelsan** [comment]
I think that a comparasion of the different approaches in the same way of the Spectral Clustering Example would be great. It could answer questions like: "how well is dask grid search implementation when compared to sklearn?"

**Comment by mrocklin** [comment]
It looks like @TomAugspurger is doing some work to describe scalability here: https://github.com/dask/dask-ml/pull/111

I encourage people to engage on that PR
