### ISSUE TITLE
dask for GSOC

### ISSUE THREAD

**Issue by karan1276** [dask/dask-ml#128]
I am a student, and i do a lot of ML on kaggle. Having a distributed library for ml is really needed, i am sure dask ml will dominate the market once it's out there. 

Just a suggestion, apply for gsoc. You will get a lot of students who want to work on this :)

good luck

**Comment by mrocklin** [comment]
Hi @karan1276 , 

Thanks for your note.  I'm a big fan of the GSOC program, and used to mentor for other projects.  My experience is that it's not difficult to apply for GSOC support, but that it's more difficult to find mentors with enough time to properly guide a student.  I'd be happy to learn that we had mentors here.  Are there any people out there with significant experience both with ML and developing Dask libraries and also have time to mentor students?

**Comment by TomAugspurger** [comment]
Closing since GSOC has started.
