### ISSUE TITLE
dask from_array() throws an error

### ISSUE THREAD

**Issue by rajulah** [dask/dask-ml#153]
Was trying to replicate the dask-GLM from this notebook (http://nbviewer.jupyter.org/gist/anonymous/15742155693794ddd31ea85b654cbc7e) taken from Matthew Rocklins weekly notes on dask (http://scipy26.rssing.com/chan-51207303/all_p3.html).
However the below line throws me an error that 'Dataframe' has no attribute 'shape'
dX = da.from_array(X, chunks=(K, X.shape[-1]))
![image](https://user-images.githubusercontent.com/9089132/37832382-6ce59234-2ece-11e8-936e-d4e75e391345.png)

dask dataframe's source code has dataframe.shape in it in some line according to the error thrown, but in the documentation of dask dataframe, there is no dask.shape() while it is there in pandas dataframe

**Comment by mrocklin** [comment]
In that example it looks like X is a numpy array caused obtained from calling `df.values`

**Comment by TomAugspurger** [comment]
@rajulah I think @mrocklin's diagnosis is correct. In the original example, `X` is a pandas DataFrame.

Let us know if that wasn't the issue.
