### ISSUE TITLE
train_test_split throws an error depending on how array chunked

### ISSUE THREAD

**Issue by stsievert** [dask/dask-ml#180]
I get an unexpected error depending on how the array is chunked. I found a solution, but I'm unsure what error message to throw or how to check for it (the reason I'm submitting an issue, not a PR).

As expected, this code passes and does not through any errors:

``` python
import numpy as np
import dask.array as da
from dask_ml.model_selection import train_test_split

n, d = 110, 40
X = np.random.randn(n, d)
y = np.sign(np.random.randn(n)).astype(np.int64)

def find_bug(X, y, chunks):
    dX = da.from_array(X, chunks)
    dy = da.from_array(y, chunks[0] if isinstance(chunks, tuple) else chunks)
    try:
        X_train, X_val, y_train, y_val = train_test_split(dX, dy, random_state=42)
    except:
        print('failed with chunks =', chunks)

find_bug(X, y, d)
find_bug(X, y, (n//8, d))
```

However, both of these function evaluations fail:

``` python-shell
>>> find_bug(X, y, d-1)
failed with chunks = 39
>>> find_bug(X, y, (n//8, d-1))
failed with chunks = (13, 39)
```

They fail with a traceback of

``` python-traceback
Traceback (most recent call last):
  File "daskmltraintestbug.py", line 19, in <module>
    X_train, X_val, y_train, y_val = train_test_split(dX, dy)
  File "/Users/ssievert/anaconda3/lib/python3.6/site-packages/dask_ml-...dask_ml/model_selection/_split.py", line 274, in train_test_split
    train_idx, test_idx = next(splitter.split(*arrays))
  File "/Users/ssievert/anaconda3/lib/python3.6/site-packages/dask_ml-.../dask_ml/model_selection/_split.py", line 134, in split
    X = check_array(X)
  File "/Users/ssievert/anaconda3/lib/python3.6/site-packages/dask_ml-.../dask_ml/utils.py", line 122, in check_array
    raise TypeError
TypeError
```

I am dask-ml master branch, commit f0b973793d3edb5445c925c372e36622fcd8906f

**Comment by TomAugspurger** [comment]
Sorry about the bad (non-existent) error message, I forgot to write a proper one.

`train_test_split` currently only works on arrays that are chunked along the first axis only. That was mainly just for quickly implementing something. I suspect it could be fixed properly without too much effort.

**Comment by TomAugspurger** [comment]
#181 will have an actual error message.

If you need chunks along multiple axes I can implement that properly.

**Comment by stsievert** [comment]
I'm satisified with this error message: it explains the problem, and provides a solution. I'm closing this issue.
