### ISSUE TITLE
StandardScaler: TypeError: 'Series' object does not support item assignment

### ISSUE THREAD

**Issue by dma092** [dask/dask-ml#214]
As in the title , I am getting this error while running the standardscaler.
I also run the same Minmaxscaler on the same dask dataframe to check if there are problems with it.
![image](https://user-images.githubusercontent.com/15647015/41594143-b266fa30-73c2-11e8-8d04-75b700a651ae.png)

**Comment by dma092** [comment]
@TomAugspurger  : I am using version 0.4.1

**Comment by TomAugspurger** [comment]
Could you try with 0.6.0?

**Comment by dma092** [comment]
problem solved with 0.6.0
