### ISSUE TITLE
Incremental learning example on dask-examples

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ml#233]
It would be nice to see an example using the `Incremental` meta-estimator on the dask-examples binder site.  This would ideally show smooth operation of a single incremental learner, discuss the tradeoffs, and then maybe go into hyper-parameter estimation, either with GridSearchCV, manual training, or Hyperband.

It would also be useful for this to be smoothly runnable on [dask-examples](https://github.com/dask/dask-examples#contributing).

**Comment by mrocklin** [comment]
@TomAugspurger might also have a small example for this somewhere that could be easily modified to fit within the dask-examples restrictions.

**Comment by TomAugspurger** [comment]
https://gist.github.com/7334e07dcad8744348f8d614eb622e8d

**Comment by stsievert** [comment]
https://github.com/dask/dask-examples/pull/15

**Comment by stsievert** [comment]
This is closed by https://github.com/dask/dask-examples/pull/15, correct?

**Comment by mrocklin** [comment]
Yes, thanks
