### ISSUE TITLE
Incremental.partial_fit does not randomly shuffle blocks on repeated calls

### ISSUE THREAD

**Issue by stsievert** [dask/dask-ml#274]
Or blocks are always fed into `estimator.partial_fit` in the same order. Here's an example of repeated `partial_fit` calls (interspersed by `score` calls):

<img width="617" alt="screen shot 2018-07-03 at 11 29 11 am" src="https://user-images.githubusercontent.com/1320475/42232690-bce43596-7ede-11e8-9700-0cbaee4edba6.png">

I am sure this does not matter for the test data we create, but it might matter for other data (e.g., time series).

**Comment by stsievert** [comment]
I tried modifying https://github.com/dask/dask-ml/blob/d80ae33987fd2a8ee65f2e516d34129c67eb60f0/dask_ml/_partial.py#L182, but am unsure how to make the elements in `dask.shareddict` ordered.

**Comment by mrocklin** [comment]
The line to change for this is probably 178 here:

https://github.com/dask/dask-ml/blob/d80ae33987fd2a8ee65f2e516d34129c67eb60f0/dask_ml/_partial.py#L177-L180

We want to create a random ordering:

```python
import random
order = list(range(x.num_blocks[0]))
random.shuffle(order)
```

And then we want to index the `order[i]`th block of x

    ... (x.name, order[i], 0) ...

**Comment by mrocklin** [comment]
I think that that should suffice.

**Comment by mrocklin** [comment]
We will also want to include that ordering in the tokenize call to make sure that we come up with a different name.  We might want to allow users to opt-out of this behavior.
