### ISSUE TITLE
Use case with deep-learning frameworks: prediction in parallel

### ISSUE THREAD

**Issue by lesteve** [dask/dask-ml#281]
Here is the use case that some people around me are trying to tackle with dask: object detection on many videos in parallel.

* we have a pretrained model (using TensorFlow or PyTorch typically) that does object detection
* we have plenty of videos we want to run your model on, and we want to parallelize over the videos
* we are using dask-jobqueue on a SGE cluster

Here are the problems/questions we have so far:
* is there a way to make sure that the model is created on each worker, rather than created on one worker and then serialized and sent across the network (a lot slower 2-3 minutes vs 20s in our early attempts) ? Our attempts look like this:
```py
# this creates the model on one worker and then serializes it and sends it across the network
model = client.submit(create_model)
client.map(run_object_detection, [model] * n_videos, videos)
```

```py
# this adds a dummy argument to create_model, but that does not seem very clean
models = client.map(create_model, range(4))
client.map(run_object_detection, models, videos)
```
* in the log files from SGE (i.e. `dask-worker.o<job_id>` files), we get `Event loop was unresponsive in Worker for 41.37s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.`. Should we worry about that? Googling about this I found this [SO answer](https://stackoverflow.com/a/48087194) and this [github comment](https://github.com/dask/dask/issues/2866#issuecomment-380874475) both by @mrocklin. IIUC I should not worry about this too much until this starts becoming a problem.
* we have some `print` statement in our functions (`create_model`, `run_object_detection`) but they did not seem to appear anywhere in the SGE logs. Not sure what the advice is to do lightweight debugging like this.

**Comment by mrocklin** [comment]
For the first problem, you might first try the following:

```python
model = client.submit(create_model)
dask.distributed.wait(model)
client.replicate(model)
client.map(run_object_detection, [model] * n_videos, videos)
```

This still moves the model around, but avoids all of your workers hammering the one that has it right away.  It might improve things (this is also fixed in https://github.com/dask/distributed/pull/2092)

I'm curious, how large is your model?  Can you investigate how long it takes to serialize, and how large the result is?

```python
%time len(pickle.dumps(model))
```

41 seconds is a long time to wait for something.  During this time the worker is unable to respond to requests from other workers.  *Something* is holding onto the GIL.  It might be interesting to find out what.

I would expect print statements to show up in SGE's logs.  An alternative would be to use `distributed.worker.logger`, whose outputs will also be available in the dashboard in the "info" pages (look for the the "logs" links on the right of the main info page)

**Comment by mrocklin** [comment]
Can I ask for `%time len(pickle.dumps(model))` ?

I wonder what is taking so long.  Is it serializing?  Is it a really big blob to move around?  It might also be interesting to look at profile output with something like the `%prun` magic or snakeviz.

**Comment by lesteve** [comment]
Not entirely sure but I think it is serializing when the model is on the GPU. It feels like there is something to do by combining http://distributed.readthedocs.io/en/latest/serialization.html#dask-serialization-family and https://pytorch.org/docs/stable/notes/serialization.html?highlight=saving%20models.

A simple snippet that reproduces a similar behaviour:

```py
from torchvision.models.resnet import resnet18
model = resnet18(pretrained=True)
model.cuda()
%time len(pickle.dumps(model)) / 1e6
```

```
Out[7]: 105.332536
CPU times: user 1min 18s, sys: 19 s, total: 1min 37s
Wall time: 1min 37s
```

**Comment by mrocklin** [comment]
I'm inclined to first try to solve the problem there.  We're serializing at
1MB/s.  No part of the pipeline needs to be that slow.

**Comment by lesteve** [comment]
> I'm inclined to first try to solve the problem there. We're serializing at 1MB/s. No part of the pipeline needs to be that slow.

Not entirely sure what you mean by "there", do you mean it should be fixed inside PyTorch? Do you mean it should be fixed through dask serialization families?

**Comment by mrocklin** [comment]
See https://github.com/pytorch/pytorch/issues/9168

Short term the right thing to do is probably to special-case PyTorch with the class-based dask serialization family: http://distributed.readthedocs.io/en/latest/serialization.html#id2

This comment has sufficient information for both PyTorch models and tensors: https://github.com/pytorch/pytorch/issues/9168#issuecomment-402516694

**Comment by mrocklin** [comment]
A naive implementation is probably as follows:

```python
from distributed.serialize import register_serialization

def serialize(model):
    import torch, io
    bio = io.BytesIO()
    torch.save(obj, bio)
    header = {}
    frames = [bio.getvalue()]
    return header, frames

def deserialize(header, frames):
    import torch, io
    [frame] = frames
    bio = io.BytesIO(frame)
    return torch.load(bio)

from distributed.protocol.serialize import register_serialization
register_serialization('torch.Tensor', serialize, deserialize)
register_serialization('...', serialize, deserialize)
...
```

In the future it would be nice to avoid the torch.save process and instead just pass buffers around to avoid copies, but it looks like this will get us up to about 1GB/s, which is probably enough for standard cases.

**Comment by mrocklin** [comment]
It looks like your model object though is a special subclass, which is a bit unpleasant.  The dask class based serialization doesn't do any kind of inheritance checking. 

```python
In [1]: from torchvision.models.resnet import resnet18
   ...: model = resnet18(pretrained=True)
   ...: type(model).mro()
   ...: 
   ...: 
Out[1]: [torchvision.models.resnet.ResNet, torch.nn.modules.module.Module, object]
```

**Comment by lesteve** [comment]
Thanks a lot for the additional info!

So IIUC I can not register a custom serialization for `torch.nn.modules.module.Module` for example and expect that it works for the `resnet18` instance?

I am guessing that it does not magically work on attributes either (a bit of a joblib bias here for sure ...). So I can not register a custom serialization for `torch.Tensor` and expect to have an effect on the `resnet18` instance?

Out of curiosity, do I need to register the custom serialization on all the workers, e.g. by using `client.run`?

**Comment by mrocklin** [comment]
@lesteve, if you're comfortable living with short-term patches, my current recommendation is just to patch your installation of PyTorch with the solution in https://github.com/pytorch/pytorch/pull/9184.  It's five lines and solves the problem.  See https://github.com/pytorch/pytorch/pull/9184#issuecomment-402818836

**Comment by mrocklin** [comment]
@lesteve I think that this has now been resolved upstream.  With https://github.com/pytorch/pytorch/pull/9184 I get 1 GB/s serialization bandwidths rather than 50MB/s (CPU).  My guess is that this will also resolve the GPU serialization issue as well, but it would be good to check.

**Comment by lesteve** [comment]
Great, thanks a lot @mrocklin! I haven't got around trying out your suggestions yet but it's good to know that the slow pickling problem has been fixed in PyTorch.

Something I realised recently is that keras models are not be picklable in general (there is a 2-week old PR https://github.com/keras-team/keras/pull/10483 to fix that) so the custom dask serialization may come in handy, e.g.:
```py
import pickle
from keras.applications.resnet50 import ResNet50

resnet50 = ResNet50()
pickle.dumps(resnet50)
```

```
TypeError: can't pickle _thread.lock objects
```

**Comment by mrocklin** [comment]
I think that @bnaul may have already solved that in Dask.  There is a keras
solution in distributed/protocol/serialize/keras.py

But we could probably also do the same trick upstream and fix things for
them as well.

**Comment by lesteve** [comment]
Nice, great to know!

**Comment by lesteve** [comment]
Closing this one, since most of the problems have been addressed.

**Comment by mrocklin** [comment]
Thanks for raising @lesteve
