### ISSUE TITLE
Confusing documentation link on top of page

### ISSUE THREAD

**Issue by stsievert** [dask/dask-ml#282]
I would expect the link at the top of the page to link to https://dask-ml.readthedocs.io/en/latest/index.html, not https://dask.pydata.org/en/latest/

Here's a picture of what I mean:

<img width="1018" alt="screen shot 2018-07-04 at 3 43 32 pm" src="https://user-images.githubusercontent.com/1320475/42293616-1a76ab20-7fcb-11e8-83be-02c9519969eb.png">

I would modify this myself, but PRs don't work for this.

**Comment by TomAugspurger** [comment]
Fixed!

**Comment by stsievert** [comment]
Thanks!
