### ISSUE TITLE
Unlisted requirement on packaging?

### ISSUE THREAD

**Issue by jimmywan** [dask/dask-ml#290]
I recently tried to update some pre-existing code that was using dask_searchcv to use dask_ml, but my 1-2 line change didn't seem to take.

In particular, I received this error which seemed to indicate that I need `packaging` ([this](https://packaging.pypa.io/en/latest/)?) to run. Is this expected?

```
  File "/opt/python/common/model/runner.py", line 11, in <module>
    from dask_ml.model_selection import GridSearchCV
  File "/usr/local/lib/python3.6/site-packages/dask_ml/model_selection/__init__.py", line 6, in <module>
    from ._search import (
  File "/usr/local/lib/python3.6/site-packages/dask_ml/model_selection/_search.py", line 9, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by TomAugspurger** [comment]
Thanks. How'd you install dask-ml?

**Comment by TomAugspurger** [comment]
We should probably include setuptools in https://github.com/dask/dask-ml/blob/master/setup.py#L13 directly.

**Comment by jimmywan** [comment]
> How'd you install dask-ml?

I did this:
`pip install dask-ml[xgboost]`
