### ISSUE TITLE
Bump required version of dask

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-ml#293]
The dask.array.learn transition means we have a hard requirement on Dask's minimum version. Should require Dask >= 0.18.0 I think.

**Comment by jrbourbeau** [comment]
I don't totally follow along here. I could definitely be missing something, but it looks like `dask-ml` has removed all dependencies on `dask.array.learn`, so why would we need to bump the minimum required `dask` version?

**Comment by TomAugspurger** [comment]
Sorry, you're right. I had this backwards.
