### ISSUE TITLE
Update joblib-distributed documentation

### ISSUE THREAD

**Issue by js3711** [dask/dask-ml#307]
In the joblib-distributed [documentation](http://dask-ml.readthedocs.io/en/latest/examples/joblib-distributed.html) 

```python
forest = ExtraTreesClassifier(n_estimators=1000,
                              max_features=128,
                              n_jobs=-1,
                              random_state=0;

t0 = time()
with joblib.parallel_backend('dask.distributed', scheduler_host=client.scheduler.address):
    forest.fit(X, y)

print("done in %0.3fs" % (time() - t0))
```
ExtraTreesClassifier is used as an example of using dask as a backend for joblib.  This feature will not work until scikit-learn v0.20.

The documentation should be updated to use something like scikit-learns gridsearch as an example; it will actually use the dask backend. See discussion in #231

**Comment by TomAugspurger** [comment]
We now require scikit-learn>=0.20, so this ins't an issue anymore.
