### ISSUE TITLE
Collect routines from other packages?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ml#32]
In some cases we import routines from other packages.  In some cases we don't.

For example we import LogisticRegression from dask_glm but don't import GridSearchCV from dask_searchcv.  Which approach should we take here?  I'm slightly inclined to import from everywhere and consolidate here.

**Comment by TomAugspurger** [comment]
Agreed. dask-search is being worked on at https://github.com/dask/dask-ml/pull/15 (waiting on a PR in dask-search-cv).

**Comment by TomAugspurger** [comment]
I think this was resolved in #29 and #15
