### ISSUE TITLE
Set minimum required version of Dask

### ISSUE THREAD

**Issue by kevin-fang** [dask/dask-ml#328]
I'm trying to do a simple Grid Search to find the best params for a LinearSVC in scikit-learn:

```python
from sklearn.svm import LinearSVC
from dask_ml.model_selection import GridSearchCV
crange = np.logspace(-2, 1, 10).tolist()
param_space = {'C': crange,
               'class_weight': [None, 'balanced']}

model = LinearSVC(penalty='l1', dual=False, verbose=1, max_iter=1000)

search = GridSearchCV(model, param_space, cv=5, n_jobs=5)
search.fit(encoded, blood_types)
print(search.best_params_)
```

However, after running the fit it gives me this:
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f79a6f8fb842> in <module>()
      8 
      9 search = GridSearchCV(model, param_space, cv=5, n_jobs=5)
---> 10 search.fit(encoded, blood_types)
     11 print(search.best_params_)

/home/kfang/.local/lib/python2.7/site-packages/dask_ml/model_selection/_search.pyc in fit(self, X, y, groups, **fit_params)
    839 
    840         n_jobs = _normalize_n_jobs(self.n_jobs)
--> 841         scheduler = dask.base.get_scheduler(
    842             scheduler=(self.scheduler
    843                        if isinstance(self.scheduler, str)

AttributeError: 'module' object has no attribute 'get_scheduler'
```
I'm using dask_ml version `0.7.0`

**Comment by TomAugspurger** [comment]
What version of dask. I suspect if you upgrade that things will work out.

**Comment by kevin-fang** [comment]
Yes, you're right. It looks like it was changed in this commit https://github.com/dask/dask/commit/24fda1faf0da80a3d839d917372aeb7cd421e59c#diff-e5d233d0b11c3223493928fdb5fb35ceR26, so dask 0.17.5. I was running dask 0.17.0.

**Comment by TomAugspurger** [comment]
Currently, dask-ml doesn't set a minimum bound on dask, even though we use features from recent versions. Once the development of dask and dask-ml slow a bit, we'll want to set that minimum bound and test against it. But for now I'm ok with pushing users to upgrade :)

**Comment by mrocklin** [comment]
Why not set a minimum bound on the next dask-ml release?  This bound could
be pretty aggressive.  This seems cheap to do.

**Comment by TomAugspurger** [comment]
That's fine by me.
