### ISSUE TITLE
Rename to dask_ml?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ml#33]
Most dask packages follow the following naming convention:

1.  dask-foo for package name on PyPI, and github
2.  dask_foo for import name in Python

The `dask-ml` package is currently imported as `daskml` rather than `dask_ml`.  The underscore is a bit of a pain, so I can see how the current name would be preferred.  Still though, I thought I'd bring this up.  We may want to switch for conformity's sake.

cc @TomAugspurger @jcrist

**Comment by TomAugspurger** [comment]
+1. I've typo-ed this so many times.
