### ISSUE TITLE
How to apply model on big data

### ISSUE THREAD

**Issue by pullanagari** [dask/dask-ml#332]
Hi, I am using small training data for creating a model then applying on big data. 
I use following code for model development, anyone can please provide code to predict on large dataset using daskml.
Appreciate your help in advance.

import dask_ml.joblib  # registers joblib plugin
from sklearn.externals.joblib import parallel_backend
from sklearn.grid_search import RandomizedSearchCV
from sklearn.svm import SVC

param_space = {
    'C': np.logspace(-6, 6, 13),
    'gamma': np.logspace(-8, 8, 17),
    'tol': np.logspace(-4, -1, 4),
    'class_weight': [None, 'balanced'],
}

model = SVC(kernel='rbf')
search = RandomizedSearchCV(model, param_space, cv=3, n_iter=5, verbose=10)

with parallel_backend('dask'):
    search.fit(x, y)

**Comment by pullanagari** [comment]
Hi Tom,

Thanks for your reply, i used the following code to execute and working well.
from dask_ml.wrappers import ParallelPostFit
from sklearn.externals.joblib import parallel_backend
from sklearn.grid_search import RandomizedSearchCV
from sklearn.svm import SVC
model = ParallelPostFit(SVC(kernel='rbf'))
model.fit(x,y)

just wondering, can we use parallelpostfit for finding optimal hyperparamters using gridsearch and corss-validations  ?
If can't use how to enter the optimal hyperparameter values

**Comment by TomAugspurger** [comment]
ParallelPostFit doesn’t affect training at all. You can use randomized search like before. You may have to pretend the parameter names with estimator__. This would make for a good example in the docs.

________________________________

**Comment by TomAugspurger** [comment]
```python
import dask_ml.joblib # registers joblib plugin
from dask_ml.wrappers import ParallelPostFit
from dask.distributed import Client
import numpy as np
from sklearn.externals.joblib import parallel_backend
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVC
import sklearn.datasets


x, y = sklearn.datasets.make_classification()

client = Client()

param_space = {
    'estimator__C': np.logspace(-6, 6, 13),
    'estimator__gamma': np.logspace(-8, 8, 17),
    'estimator__tol': np.logspace(-4, -1, 4),
    'estimator__class_weight': [None, 'balanced'],
}

model = ParallelPostFit(SVC(kernel='rbf'))
search = RandomizedSearchCV(model, param_space, cv=3, n_iter=5, verbose=10)

with parallel_backend('dask', scatter=[x, y]):
    search.fit(x, y)
```

Are you running this on a cluster, or single machine? The distributed joblib backend won't give any performance improvements on a single machine.

**Comment by pullanagari** [comment]
Hi Tom,

It is working well and processing the data in a short time taking only 2-3 min to analysis a big matrix 4000*448, though i am suing a single machine with 12 cores.
Thanks for your feedback.

I have another issue, after training the model applying on big data. After applying the model when i tried to convert into dask frame to numpy frame i am getting following error.

[issue.docx](https://github.com/dask/dask-ml/files/2284838/issue.docx)

**Comment by TomAugspurger** [comment]
Won't have time to look at a word file, but when you predict for a large
input you get back a dask array or dataframe. If you try to convert that to
a NumPy array it has to fit in memory on a single machine.

**Comment by pullanagari** [comment]
Thanks Tom, it is working well now
