### ISSUE TITLE
cann't import Linearregression from dask_ml

### ISSUE THREAD

**Issue by rahulbhas86** [dask/dask-ml#341]
The error message --

```
---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-34-b77db0f368b1> in <module>()
----> 1 from dask_ml.linear_model import LinearRegression

~\Anaconda3\lib\site-packages\dask_ml\__init__.py in <module>()
      2 
      3 try:
----> 4     __version__ = get_distribution(__name__).version
      5 except DistributionNotFound:
      6     # package is not installed

~\Anaconda3\lib\site-packages\pkg_resources\__init__.py in get_distribution(dist)
    562         dist = Requirement.parse(dist)
    563     if isinstance(dist, Requirement):
--> 564         dist = get_provider(dist)
    565     if not isinstance(dist, Distribution):
    566         raise TypeError("Expected string, Requirement, or Distribution", dist)

~\Anaconda3\lib\site-packages\pkg_resources\__init__.py in get_provider(moduleOrReq)
    434     """Return an IResourceProvider for the named module or requirement"""
    435     if isinstance(moduleOrReq, Requirement):
--> 436         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    437     try:
    438         module = sys.modules[moduleOrReq]

~\Anaconda3\lib\site-packages\pkg_resources\__init__.py in require(self, *requirements)
    982         included, even if they were already activated in this working set.
    983         """
--> 984         needed = self.resolve(parse_requirements(requirements))
    985 
    986         for dist in needed:

~\Anaconda3\lib\site-packages\pkg_resources\__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    873                 # Oops, the "best" so far conflicts with a dependency
    874                 dependent_req = required_by[req]
--> 875                 raise VersionConflict(dist, req).with_context(dependent_req)
    876 
    877             # push the new requirements onto the stack

ContextualVersionConflict: (dask 0.16.1 (c:\users\acer pc\anaconda3\lib\site-packages), Requirement.parse('dask[array]>=0.18.2'), {'dask-ml'})

```

**Comment by TomAugspurger** [comment]
What version of dask-ml? The latest release (0.8.0) fixed a packaging issue.

**Comment by rahulbhas86** [comment]
I have dask_ml version 0.8.0
other packages-
dask     0.16.1 py36_0
dask 0.18.2 pip
dask-core  0.16.1 py36_0
dask-glm 0.1.0
dask-ml  0.8.0
dask-searchcv 0.2.0
I installed dask by
pip install "dask[complete]"
then
pip install dask-ml
pip install dask-searchcv

**Comment by TomAugspurger** [comment]
You shouldn't need dask-searchcv any more.

Can you try creating a new environment?

conda create -n dask-ml-test python=3 dask-ml

and seeing if that works? It's possible that using pip and conda together
has corrupted some metadata.

**Comment by rahulbhas86** [comment]
Yes, it worked fine under new env
but when I try to fit gridsearch another error popped up, for your reference, I am using through this dask tutorial - https://www.analyticsvidhya.com/blog/2018/08/dask-big-datasets-machine_learning-python

error is -

IndexError                                Traceback (most recent call last)
<ipython-input-23-4768d701af47> in <module>()
----> 1 grid_search.fit(data, target)

~\Anaconda3\lib\site-packages\dask_searchcv\model_selection.py in fit(self, X, y, groups, **fit_params)
    865         scheduler = _normalize_scheduler(self.scheduler, n_jobs)
    866 
--> 867         out = scheduler(dsk, keys, num_workers=n_jobs)
    868 
    869         results = handle_deprecated_train_score(out[0], self.return_train_score)

~\Anaconda3\lib\site-packages\dask\threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     73     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     74                         cache=cache, get_id=_thread_get_id,
---> 75                         pack_exception=pack_exception, **kwargs)
     76 
     77     # Cleanup pools associated to dead threads

~\Anaconda3\lib\site-packages\dask\local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    503                         _execute_task(task, data)  # Re-execute locally
    504                     else:
--> 505                         raise_exception(exc, tb)
    506                 res, worker_id = loads(res_info)
    507                 state['cache'][key] = res

~\Anaconda3\lib\site-packages\dask\compatibility.py in reraise(exc, tb)
     67         if exc.__traceback__ is not tb:
     68             raise exc.with_traceback(tb)
---> 69         raise exc
     70 
     71 else:

~\Anaconda3\lib\site-packages\dask\local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    272     try:
    273         task, data = loads(task_info)
--> 274         result = _execute_task(task, data)
    275         id = get_id()
    276         result = dumps((result, id))

~\Anaconda3\lib\site-packages\dask\local.py in _execute_task(arg, cache, dsk)
    253         func, args = arg[0], arg[1:]
    254         args2 = [_execute_task(a, cache) for a in args]
--> 255         return func(*args2)
    256     elif not ishashable(arg):
    257         return arg

~\Anaconda3\lib\site-packages\dask_searchcv\methods.py in fit_and_score(est, cv, X, y, n, scorer, error_score, fields, params, fit_params, return_train_score)
    278     y_test = cv.extract(X, y, n, False, False)
    279     est_and_time = fit(est, X_train, y_train, error_score,
--> 280                        fields, params, fit_params)
    281     if not return_train_score:
    282         X_train = y_train = None

~\Anaconda3\lib\site-packages\dask_searchcv\methods.py in fit(est, X, y, error_score, fields, params, fit_params)
    214         try:
    215             est = set_params(est, fields, params)
--> 216             est.fit(X, y, **fit_params)
    217         except Exception as e:
    218             if error_score == 'raise':

~\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py in fit(self, X, y, sample_weight)
    314             for i in range(n_more_estimators):
    315                 tree = self._make_estimator(append=False,
--> 316                                             random_state=random_state)
    317                 trees.append(tree)
    318 

~\Anaconda3\lib\site-packages\sklearn\ensemble\base.py in _make_estimator(self, append, random_state)
    125         estimator = clone(self.base_estimator_)
    126         estimator.set_params(**dict((p, getattr(self, p))
--> 127                                     for p in self.estimator_params))
    128 
    129         if random_state is not None:

~\Anaconda3\lib\site-packages\sklearn\base.py in set_params(self, **params)
    263             # Simple optimization to gain speed (inspect is slow)
    264             return self
--> 265         valid_params = self.get_params(deep=True)
    266 
    267         nested_params = defaultdict(dict)  # grouped by prefix

~\Anaconda3\lib\site-packages\sklearn\base.py in get_params(self, deep)
    239                     continue
    240             finally:
--> 241                 warnings.filters.pop(0)
    242 
    243             # XXX: should we rather test if an instance of estimator?

IndexError: pop from empty list

**Comment by TomAugspurger** [comment]
Glad to hear it.

That second error is a thread-safety issue in scikit-learn. It's been fixed in master and should be in the next release.
