### ISSUE TITLE
Add a BlockTransformer helper

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-ml#366]
This would be similar in spirit to http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html#sklearn.preprocessing.FunctionTransformer

Users provide a `func` that is assumed to operate on ndarrays / pandas dataframes. The `BlockTransformer` will take care of mapping it to each block / partition.

We may need some information from the user when the function changes dtype / shape.

**Comment by datajanko** [comment]
May I work on this as well?

**Comment by TomAugspurger** [comment]
I was going to suggest it for you. I think it'll end up being quite similar to the `PolynomialTransformer`. In the end, you may be able to re-implement the PolynomialTransformer as an instance of `BlockTransformer`, but maybe not. LMK if you need help getting started.

**Comment by datajanko** [comment]
Perfect. I also think it's very similar.

**Comment by datajanko** [comment]
Assume you have a function like

```
def f(arr):
    return arr[:,[0]]+arr[:,[1]]
```
putting such a function into `map_blocks` will only work if all blocks have at least a width of 2.
As data frames are only partitions w.r.t rows,  I wouldn't have a problem width allowing functions that can operate on full rows.

I think one could then also infer the output shape, by simply running the function on the first row (and potentially making the transformer "stateful" only to be able to throw errors).

So what kinds of functions should be applicable here?

**Comment by datajanko** [comment]
@TomAugspurger any thoughts on my last comment? which kind (input shape, output shape) of functions shall we allow? I think it will be quite easy, to accept functions that use information on a specific row or just on a cell will be quite easy (Poly transformer takes information from a row). However, we'd need to enforce for numpy arrays, that blocks have the width of the array to avoid effects as shown above.

Functions that take the information of all rows for a column probably will be more difficult to implement.

**Comment by TomAugspurger** [comment]
The user-provided function should operate on ndarrays / pandas data frames.

In BlockTransformer.transform, dask-ml will ensure that dask Arrays are only partitioned along the samples using `dask_ml.utils.check_array` before calling `X.map_blocks`.

I'd say let's just handle the easy things right now. Anything where dask's metadata inference fails can I think be ignored for now.

> Functions that take the information of all rows for a column probably will be more difficult to implement.


Right, those functions wouldn't work with this helper. This is just for the class of estimators where 

1. They're stateless (fit does nothing)
2. They can transform blockwise

**Comment by datajanko** [comment]
Sorry, for not coming back earlier to this. I realized that FunctionTransformer is in a separate module. Should I also create a new module here or maybe also put it in e.g. `data.py`?

**Comment by TomAugspurger** [comment]
New module seems reasonable.

**Comment by TomAugspurger** [comment]
But we’ll import it in preprocessing.__init__
