### ISSUE TITLE
Possible bug in train_test_split()

### ISSUE THREAD

**Issue by Keyeoh** [dask/dask-ml#379]
Hi everybody,

While trying to use the train_test_split() implemented in dask-ml on a Dask DataFrame I have previously generated, I get the following error:

> Traceback (most recent call last):
  File "<input>", line 11, in <module>
  File "<input>", line 116, in fit
  File "<input>", line 97, in partition_train_test
  File "C:\Users\Y0644483\AppData\Local\Continuum\miniconda3\envs\poc_long\lib\site-packages\dask_ml\model_selection\_split.py", line 430, in train_test_split
    rng = rng.randint(0, 2 ** 32)
  File "mtrand.pyx", line 991, in mtrand.RandomState.randint
ValueError: high is out of bounds for int32

Looking into the source code file _split.py, I have noticed the following:

     rng = check_random_state(random_state)
        rng = rng.randint(0, 2 ** 32)
        return list(
            itertools.chain.from_iterable(
                arr.random_split([train_size, test_size], random_state=rng)
                for arr in arrays
            )
        )

If I execute the following code, I can reproduce the same error:

    import sklearn.utils
    rng = sklearn.utils.check_random_state(2032)
    rng.randint(0, 2 ** 32)
    Traceback (most recent call last):
      File "<input>", line 4, in <module>
      File "mtrand.pyx", line 991, in mtrand.RandomState.randint
    ValueError: high is out of bounds for int32

Which is easily fixed by supplying a dtype parameter:

    rng.randint(0,2 ** 32, dtype='int64')
    3653591254

I do not know if there is something I am missing, but I thought it might be interesting to ask...

Any help or hint would be much appreciated.

Regards, and keep the good work!

BTW, I am using a Conda environment with python 3.6.6, dask 0.19.2 and dask-ml 0.10.0

**Comment by TomAugspurger** [comment]
Same issue as https://github.com/dask/dask-ml/issues/378 I think.

Given that you're the second person to report this in a week, we really need to setup testing on a 32-bit platform. I'll try to get to these next week.

FYI, the workaround is to to pass a seed to `train_test_split`

**Comment by rlwphd** [comment]
Hey Tom,

I just ran into this same issue of getting the ValueError: high is out of bounds for int32 yesterday when running test_train_split. I am using up to date versions of dask_ml (0.12.0) and dask (1.1.4). I am using Anacoda on Windows with python 3.7. Also data is dask arrays.

`X_train, X_test, y_train, y_test = train_test_split(train_data, y_train_data, random_state=0)
Traceback (most recent call last):

  File "<ipython-input-16-114b1dbd38ee>", line 1, in <module>
    X_train, X_test, y_train, y_test = train_test_split(train_data, y_train_data, random_state=0)

  File "C:\Users\fastb\Anaconda3\lib\site-packages\dask_ml\model_selection\_split.py", line 449, in train_test_split
    train_idx, test_idx = next(splitter.split(*arrays))

  File "C:\Users\fastb\Anaconda3\lib\site-packages\dask_ml\model_selection\_split.py", line 156, in split
    seeds = draw_seed(rng, 0, 2 ** 32 - 1, size=len(X.chunks[0]), dtype="uint")

  File "C:\Users\fastb\Anaconda3\lib\site-packages\dask_ml\_utils.py", line 17, in draw_seed
    seed = random_state.randint(low, high, **kwargs)

  File "mtrand.pyx", line 991, in mtrand.RandomState.randint

ValueError: high is out of bounds for int32`

Tried this for:
X_train, X_test, y_train, y_test = train_test_split(train_data, y_train_data, blockwise=False, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(train_data, y_train_data)
X_train, X_test, y_train, y_test = train_test_split(train_data, y_train_data, random_state=123)
X_train, X_test, y_train, y_test = train_test_split(train_data, y_train_data, blockwise=False, random_state=123)

And all give the same error. Also tested ShuffleSplit and it gave the error as well.

So I created a new environment in Anaconda and grabbed dask-ml as an editable version and then changed the draw_seed function.

`def draw_seed(random_state, low, high=None, size=None, dtype=None, chunks=None):
    kwargs = {"size": size}
    if chunks is not None:
        kwargs["chunks"] = chunks

    seed = random_state.randint(low, high, dtype=dtype, **kwargs)
    if dtype is not None and isinstance(seed, (da.Array, np.ndarray)):
        seed = seed.astype(dtype)

    return seed`

I added the dtype=dtype into the randint function and that fixed the error. Thoughts are that the seed.astype(dtype) is being called too late to make use of the "uint" dtype provided by the _split code.

Sorry to bring back an old error.
Let me know if you need additional code to produce the error or if it appears that I am doing something wrong. Thanks!

**Comment by jrbourbeau** [comment]
Thanks for the bug report @rlwphd!

Dask array `randint` doesn't currently support the `dtype` keyword. However adding this feature was requested in https://github.com/dask/dask/issues/4579 and there's an open PR (https://github.com/dask/dask/pull/4607) to implement the `dtype` keyword. Once this is added to `randint`, a fix like you've proposed here for `dsak-ml` would be very welcome!

**Comment by rlwphd** [comment]
@jrbourbeau 
My understanding from tracing the code paths for the draw_seed function in dask_ml, leads me to believe that this instance of random_state.randint() isn't using the dask array randint but the numpy randint which does support the dtype keyword.

Code tracing...
from  _split.py
I looked at the split function which calls check_random_state to get the random state which is imported from the sklearn repository

    def split(self, X, y=None, groups=None):
        X = check_array(X)
        rng = check_random_state(self.random_state)
        for i in range(self.n_splits):
            seeds = draw_seed(rng, 0, 2 ** 32 - 1, size=len(X.chunks[0]), dtype="uint")
            if self.blockwise:
                yield self._split_blockwise(X, seeds)
            else:
                yield self._split(X)

from sklearn.utils import check_random_state

So I looked up that repository and found the check_random_state function which uses the numpy RandomState instance

def check_random_state(seed):
    """Turn seed into a np.random.RandomState instance
    Parameters
    ---------
    seed : None | int | instance of RandomState
        If seed is None, return the RandomState singleton used by np.random.
        If seed is an int, return a new RandomState instance seeded with seed.
        If seed is already a RandomState instance, return it.
        Otherwise raise ValueError.
    """
    if seed is None or seed is np.random:
        return np.random.mtrand._rand
    if isinstance(seed, (numbers.Integral, np.integer)):
        return np.random.RandomState(seed)
    if isinstance(seed, np.random.RandomState):
        return seed
    raise ValueError('%r cannot be used to seed a numpy.random.RandomState'
                     ' instance' % seed)


So I'm not sure if the dask_ml is supposed to be using a different RandomState instance but my following there leads me to believe that the dask_ml implementation is using a numpy RandomState instance which has a dtype parameter. This would then allow a simple fix of using the dtype parameter in the randint if it's not None. Hope this helps.
