### ISSUE TITLE
KMeans.fit on uncertain lengths

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ml#390]
This seems like a reasonable thing that ought to work.  Any ideas on how we could make this happen?

https://stackoverflow.com/questions/52583316/how-to-pass-dask-dataframe-as-input-to-dask-ml-models

```python
import dask.dataframe as dd
import pandas as pd
from dask_ml.cluster import KMeans

df = dd.from_pandas(pd.DataFrame({'A': [1, 2, 3, 4, 5], 
                                  'B': [6, 7, 8, 9, 10]}),
                    npartitions=2)

kmeans = KMeans()
kmeans.fit(df)
```

1.  Do we compute lengths explicitly but warn that we're doing so?
2.  Do we actually need explicit lengths (I was somewhat surprised by this)

**Comment by TomAugspurger** [comment]
> Do we compute lengths explicitly but warn that we're doing so?

With `DataFrame.to_dask_array` that's possible now. I'm not sure what's preferable.

> Do we actually need explicit lengths (I was somewhat surprised by this)

2. We could probably be smarter about this. `init='random'` for example does `idx = sorted(random_state.randint(0, len(X), size=n_clusters))`. That doesn't work for unknown lengths as written, but we could rewrite that without too much effort.

The default `init='kmeans||'`  may take a bit more effort, but at a glance it may be doable.

I think that once we get past the initialization and into Lloyd's algorithm, things will be fine.

**Comment by mrocklin** [comment]
I would be inclined to select random points in a less uniformly random way.  We might take a few points from each chunk.  If we wanted to be careful we might take several points from each chunk and the length of that chunk, and then down-select again based on those lengths.

**Comment by ianalis** [comment]
The workaround I found is to call `DataFrame.to_dask_array(lengths=True)` for models that require length, as @TomAugspurger mentioned above.

**Comment by mrocklin** [comment]
I'll plan to take a stab at this this afternoon if no one else has started.
