### ISSUE TITLE
Is it safe to replace _apply_partitionwise with map_partitions?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ml#399]
I'm not understanding why this code is here:

https://github.com/dask/dask-ml/blob/90fbe69771926b7e43a5bef99d81e268dad63e7e/dask_ml/wrappers.py#L504-L522

My guess is that it resolves some deficiency in `map_partitions`.  Is that still true?

**Comment by TomAugspurger** [comment]
From 
https://github.com/dask/dask-ml/pull/132#discussion_r166096031

> Is this something that we would want to push upstream into Dask?
 
We were blocked by `map_partitions` returning an array. We should be able to use it now.

It's funny how consistent humans can be :)

**Comment by jrbourbeau** [comment]
I think this was resolved in #400 and this issue can now be closed

**Comment by TomAugspurger** [comment]
Yes, thanks.
