### ISSUE TITLE
Can't import dask_ml.cluster

### ISSUE THREAD

**Issue by wmbm** [dask/dask-ml#410]
Perhaps I uninstalled dask incorrectly, but it complains that dask doesn't exist

I ran `conda install dask`

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-c200d62133eb> in <module>()
----> 1 import dask_ml.cluster

~/miniconda3/envs/py36_data_science/lib/python3.6/site-packages/dask_ml/cluster/__init__.py in <module>()
      1 """Unsupervised Clustering Algorithms"""
      2 
----> 3 from .minibatch import PartialMiniBatchKMeans  # noqa
      4 from .k_means import KMeans  # noqa
      5 from .spectral import SpectralClustering  # noqa

~/miniconda3/envs/py36_data_science/lib/python3.6/site-packages/dask_ml/cluster/minibatch.py in <module>()
      4 from sklearn import cluster as _cluster
      5 
----> 6 from .._partial import _BigPartialFitMixin, _copy_partial_doc
      7 
      8 

~/miniconda3/envs/py36_data_science/lib/python3.6/site-packages/dask_ml/_partial.py in <module>()
      6 from abc import ABCMeta
      7 
----> 8 import dask
      9 import numpy as np
     10 import six

ModuleNotFoundError: No module named 'dask'
```

`import dask_ml` works fine

`import dask_ml.cluster ` fails with the above error

**Comment by TomAugspurger** [comment]
Is `ModuleNotFoundError: No module named 'dask'](url)`

the actual error message? Can you try in a new environment `conda create -n tst dask dask-ml` and see if it works?

**Comment by wmbm** [comment]
Yes, this is the error message.

However, it imports correctly in the `tst `environment

**Comment by TomAugspurger** [comment]
Sounds like your environment is messed up. I would recommend throwing the old one away, or you could try removing and reinstalling packages like dask in it until it works.

**Comment by TomAugspurger** [comment]
Closing, let me know if you are still having trouble in a new environment and I'll take a closer look.
