### ISSUE TITLE
Linear Regression hangs indefinitely

### ISSUE THREAD

**Issue by jdetle** [dask/dask-ml#435]
Inside the dask-dev/dask-notebook Docker container,
if I open a notebook, clean and compose a dataframe, and try to train using features from the frame, I can't get the computation to complete.
```
from dask_ml.linear_model import LinearRegression

def train_model(facts, features_cols, target):
	# Facts has ~ 90K columns
    features = facts[features_cols].values
    target = facts[[target]].values
    model = LinearRegression()
    model.fit(features, target)
    return model
```

I can supply a minimum reproducible example if there isn't a clear issue with this code.

I get this warning continually: 
" distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 346.62 MB -- Worker memory limit: 523.97 MB "

I was thinking https://github.com/dask/distributed/issues/1866 might be related? I'm out of my element here, but I'm happy to help wherever I can.

**Comment by TomAugspurger** [comment]
Hmm I'm not sure... A reproducible example would be helpful.

I don't know how well the linear models scale to high-dimensional feature spaces. Thus far I think most of the effort went into things that are long and not too wide.

**Comment by jdetle** [comment]
I'll put it on the todo list, should be able to tackle it soon.

**Comment by TomAugspurger** [comment]
Have you had a chance to make an example @jdetle? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by jdetle** [comment]
Sorry, lost track of it.
