### ISSUE TITLE
Jupyter kernel dying using ParallelPostFit. Workers don't start.

### ISSUE THREAD

**Issue by svangogh** [dask/dask-ml#438]
I'am trying to use ParallelPostFit to wrap around a RandomForestClassfier which I am using to segment very large images (terabyte order) on a HPC.

clf = ParallelPostFit(RandomForestClassifier(criterion='gini', class_weight='balanced', n_estimators=100, n_jobs=-1)

I start a client and a cluster as follows: 

from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(queue='day', walltime='24:00:00', memory='256 GB')
from dask.distributed import Client
client = Client(cluster)

Unfortunately, when I call clf.predict(X,y), the jupyter kernel dies before the workers even start computing something. It seems that the computations are carried out on the login node (which obviously has less RAM than the images I'm using). 

Do you have any suggestions what could cause this?

Thanks!

**Comment by TomAugspurger** [comment]
Hmm... I'm not sure. `ParallelPostFit.predict` is just a thin wrapper around map_blocks or map_partitions.

Is is possible that you're passing a NumPy array to `.predict`? Or is some part of your creation of `X` or `y` done outside of dask?

**Comment by TomAugspurger** [comment]
> Could it be that this is blowing up my memory?

That should blow up the memory of your cluster though, not your client.

Can you try something simple like `X.map_blocks(len).compute()`, to see if that causes issues?

One thing I just noticed... You say that `clf.predict(X,y)` fails. That shouldn't do anything when `X` and `y` are dask arrays, since `clf.predict` is lazy for dask inputs. Is that what fails, or does `clf.predict(X,y).compute()` fail?

**Comment by svangogh** [comment]
No, clf.predict() per se works fine. It fails later when I try to actually compute it by saving the prediction to disk.

This is (part of) my code: 

This is my trained clf which I import with joblib.load():

ParallelPostFit(estimator=RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=-1, oob_score=False,
            random_state=None, verbose=0, warm_start=False),
        scoring='accuracy')

final_data = da.concatenate((gaussian3, gaussian5, gaussian10, gaussian15, gaussian20, gaussian25, gaussian30, gaussian30_2, max5, max10, max15, max20, max25, max30, min10, min15, min20, 
unif5, unif10, unif15, unif20, unif25, unif30), axis=1).rechunk(182250000/120,23)

persisted_data = client.persist(final_data)

prediction = clf.predict(persisted_data)

prediction.to_zarr('all_100.zarr') <-- here it fails

It fails while I try to save the prediction. Do you have any suggestions?

Cheers,
Stefano

**Comment by TomAugspurger** [comment]
I'm not familiar with `Array.to_zarr`. @mrocklin do you know if passing a file path like that would collect all the data to the client before writing? Or should that be written in parallel by all the workers?

**Comment by mrocklin** [comment]
Assuming that the array is chunked I would expect that to be fine.  My
understanding is that to_zarr calls da.store, which operates on the workers.

Certainly people call to_zarr with multi-terrabyte arrays pretty often.

**Comment by TomAugspurger** [comment]
Ok, thanks. @svangogh does `len(prediction)` work?

**Comment by svangogh** [comment]
Thanks for your reply! 

`len(prediction)` works


Might it be a problem that I import the trained model with joblib? Could this abolish the parallelism? 

What else might cause kernel dying? 

I'm running the notebook from the login node of a SLURMCluster on which I have 100 GB RAM. On the compute nodes I have a total of 3.75 TB RAM distributed over 15 compute nodes (24 cores per node).

My array is chunked with chunk size of about 200 MB per chunk. 

Finally, I got this warning message: 

<img width="980" alt="screenshot 2018-12-13 at 16 30 37" src="https://user-images.githubusercontent.com/40142369/49949113-2a9a5480-fef5-11e8-9beb-1955de581c5e.png">

What could it mean?

Cheers,
Stefano

**Comment by svangogh** [comment]
As I don't see any activity on the Dask dashboard, I guess that to compute and to save the prediction, the data has to easily fit in the login node's RAM.

**Comment by svangogh** [comment]
The current trained model has a size of about 2.3GB. I tried to run a prediction with a trained model with a size of 114MB, which worked perfectly in distributed mode. 

Should I use client.scatter() to somehow subdivide the random forest?

Cheers and thanks,
Stefano

**Comment by TomAugspurger** [comment]
Could you try writing a function that loads the model (from a shared file
system) and predicts all in one batch?

This is potentially similar to the issue described in
https://github.com/dask/dask-examples/issues/35#issue-356119761

**Comment by svangogh** [comment]
Hi,
you mean just using the trained model to do the prediction on a little piece of data, but without using dask chunking etc.?

**Comment by TomAugspurger** [comment]
No, I mean on the full dataset with dask arrays for chunking.

The fact that prediction works on a small model, but not on the large
model, led me to believe it may be
similar to what's happening in
https://github.com/dask/dask-examples/issues/35#issue-356119761. That post
describes using dask.delayed to not include the model in each task.

**Comment by TomAugspurger** [comment]
I'm not sure. What do you mean by "flatten the whole arrays"? A simple `da.from_zarr(...).ravel()` would not read in all the data at once.

**Comment by svangogh** [comment]
Hi Tom! Yes, sorry. I guess I used a very inefficient chunking pattern.

**Comment by TomAugspurger** [comment]
It sounds like this is resolved then.
