### ISSUE TITLE
Tornado "await wasn't used with future" leads to KeyError

### ISSUE THREAD

**Issue by mfenner1** [dask/dask-ml#446]
Apologies if I'm missing something trivial (i.e., something is not implemented in dask-ml, etc).  

I have what I hope is a simple test example to spin up and use `dask-ml`.  When running, I get the errors shown in `error.txt`.

```
from sklearn import (datasets, 
                     decomposition,
                     metrics, 
                     model_selection as skms,
                     neighbors,
                     pipeline,
                     preprocessing as skpre)
import numpy as np

from dask.distributed import Client
from sklearn.externals import joblib
client = Client()

with joblib.parallel_backend('dask'):
    iris = datasets.load_iris()
    ftrs, tgt = iris.data, iris.target
    knn    = neighbors.KNeighborsClassifier()
    pca    = decomposition.PCA()
    scaler = skpre.StandardScaler()

    pipe = pipeline.Pipeline(steps=[('scaler', scaler),
                                    ('pca', pca), 
                                    ('knn', knn)])
    cv_scores = skms.cross_val_score(pipe, ftrs, tgt, cv=10)

```

This was with a fresh `conda install dask-ml` environment (off of the main conda channel).  Installing via `conda install -c conda-forge dask-ml` appeared to lead to the same version of `dask` so I didn't pursue that.  Some relevant software versions.
```
dask                      1.0.0                    py37_0  
dask-core                 1.0.0                    py37_0  
dask-glm                  0.2.0                    py37_0  
dask-ml                   0.11.0                   py37_0 
distributed               1.25.2                   py37_0  
python                    3.7.2                haf84260_0  
scikit-learn              0.20.2           py37h27c97d8_0
```  

[error.txt](https://github.com/dask/dask-ml/files/2766275/error.txt)

**Comment by mrocklin** [comment]
Hi @mfenner1 !

I tried running this but found that there were a few terms missing like datasets, neighbors, decomposition, skpre, and skms.  What are these?  Can you includes imports that might need to exist?  Sorry if this is obvious.  I'm not familiar with your workflow.

**Comment by mfenner1** [comment]
Oh geez.  I didn't include my imports.  Sorry, I only cut one cell out of the notebook.  Apologies.  Here's a more complete version.

```
from sklearn import (datasets, 
                     decomposition,
                     metrics, 
                     model_selection as skms,
                     neighbors,
                     pipeline,
                     preprocessing as skpre)
import numpy as np

from dask.distributed import Client
from sklearn.externals import joblib
client = Client()

with joblib.parallel_backend('dask'):
    iris = datasets.load_iris()
    ftrs, tgt = iris.data, iris.target
    knn    = neighbors.KNeighborsClassifier()
    pca    = decomposition.PCA()
    scaler = skpre.StandardScaler()

    pipe = pipeline.Pipeline(steps=[('scaler', scaler),
                                    ('pca', pca), 
                                    ('knn', knn)])
    cv_scores = skms.cross_val_score(pipe, ftrs, tgt, cv=10)
```

**Comment by mrocklin** [comment]
Interestingly I'm not able to reproduce this locally.  The error log that you've attached looks interesting though.  cc'ing @ogrisel from scikit-learn/joblib who may be able to interpret it more effectively.

**Comment by mfenner1** [comment]
Cool.  I'm glad it's probably more of a versioning type problem than a fundamental show stopper.  Are there any things in that example that are more complex from joblib perspective that I could remove to produce a more minimal failure?  For example, I'll try a single train-test split instead of `cross_val_score`.

**Comment by TomAugspurger** [comment]
@mfenner1 what version of distributed?

After placing everything starting with `client = Client()` in a `main` function, and adding

```python
if __name__ == '__main__':
    main()
```

block, things seem to finish.

**Comment by mfenner1** [comment]
@TomAugspurger Thanks for jumping in.   Version of distributed:

`distributed               1.25.2                   py37_0 `

The following smaller example (no gridsearch, no pipeline) works for `cv=3` and `cv=5`.  It seems to work *sometimes* for `cv=7`.  It fails with `cv=8` or greater.
```
with joblib.parallel_backend('dask'):
    iris = datasets.load_iris()
    ftrs, tgt = iris.data, iris.target
    knn    = neighbors.KNeighborsClassifier()
    cv_scores = skms.cross_val_score(knn, ftrs, tgt, cv=10)
```

**Comment by ogrisel** [comment]
Thanks for the report.

For the record, I can also reproduce reproduce the problem using sklearn / dask / distributed / joblib master by importing joblib instead of sklearn.externals.joblib and exporting the `SKLEARN_SITE_JOBLIB=1` env variable.

**Comment by TomAugspurger** [comment]
Is this still an issue? https://github.com/dask/dask-ml/issues/446#issuecomment-455530656 doesn't reproduce an error for me.

**Comment by mfenner1** [comment]
@TomAugspurger  Sorry, I was off github for a bit and didn't see the question.  I will put testing it out on my TODO list.  Thank you.

**Comment by Juanlu001** [comment]
@camillechau found this error, just leaving a comment here so we try to get back to this and provide a reproducible example and some more info.

**Comment by ogrisel** [comment]
For the record, this issue is being investigated at: https://github.com/joblib/joblib/issues/852.

**Comment by mfenner1** [comment]
Recent update appears to have fixed this issue.  Closing for now.

**Comment by mrocklin** [comment]
Great.  Thanks for tracking this Markq
