### ISSUE TITLE
type error when fitting X,y

### ISSUE THREAD

**Issue by MichaelSchroter** [dask/dask-ml#453]
Hi All,

I have created the training set for machine learning and when trying to `fit` model it gives a value error.

The code and error is as follows.

Code:

`search.fit(train_final[X_cols_train], train_final['target'])`

output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-105-9dea7c488bbf> in <module>
----> 1 search.fit(train_final[X_cols_train], train_final['target'])

~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in fit(self, X, y, **fit_params)
    572             Additional partial fit keyword arguments for the estimator.
    573         """
--> 574         return default_client().sync(self._fit, X, y, **fit_params)
    575 
    576     @if_delegate_has_method(delegate=("best_estimator_", "estimator"))

~/env/lib/python3.5/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    671             return future
    672         else:
--> 673             return sync(self.loop, func, *args, **kwargs)
    674 
    675     def __repr__(self):

~/env/lib/python3.5/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

~/env/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/env/lib/python3.5/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/usr/lib/python3.5/asyncio/futures.py in result(self)
    291             self._tb_logger = None
    292         if self._exception is not None:
--> 293             raise self._exception
    294         return self._result
    295 

~/env/lib/python3.5/site-packages/tornado/gen.py in wrapper(*args, **kwargs)
    324                 try:
    325                     orig_stack_contexts = stack_context._state.contexts
--> 326                     yielded = next(result)
    327                     if stack_context._state.contexts is not orig_stack_contexts:
    328                         yielded = _create_future()

~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in _fit(self, X, y, **fit_params)
    522     @gen.coroutine
    523     def _fit(self, X, y, **fit_params):
--> 524         X, y = self._check_array(X, y)
    525 
    526         X_train, X_test, y_train, y_test = self._get_train_test_split(X, y)

~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in _check_array(self, X, y, **kwargs)
    437         if isinstance(y, np.ndarray):
    438             y = da.from_array(y, y.shape)
--> 439         X = check_array(X, **kwargs)
    440         kwargs["ensure_2d"] = False
    441         y = check_array(y, **kwargs)

~/env/lib/python3.5/site-packages/dask_ml/utils.py in check_array(array, *args, **kwargs)
    149     elif isinstance(array, dd.DataFrame):
    150         if not accept_dask_dataframe:
--> 151             raise TypeError("This estimator does not support dask dataframes.")
    152         # TODO: sample?
    153         return array

TypeError: This estimator does not support dask dataframes.
```

Also I would like to know when fitting data do we need to re-code string values in columns (in categorical data) to numerical data. For example if there is a column with categories `a,b,c` do we have to re-code it as for example as `1,2,3`. Furthermore if we need to do so then how do we make sure that the test set also is re-coded in the same pattern such as 1 for a and 2 for b. 

Thank you

Michael

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

You may need to convert your dask dataframe to a dask array for now.

> to re-code string values in columns (in categorical data) to numerical data.

Either http://ml.dask.org/modules/api.html#dask_ml.preprocessing.OneHotEncoder or http://ml.dask.org/modules/generated/dask_ml.preprocessing.OrdinalEncoder.html

**Comment by MichaelSchroter** [comment]
Hi, 

Sorry for that. Hope this helps.

```
import numpy as np
from dask_ml.wrappers import ParallelPostFit
params = {'estimator__alpha': np.logspace(-2, 1, num=1000),'estimator__l1_ratio': np.linspace(0, 1, num=1000),'estimator__average': [True, False]}

from sklearn.linear_model import SGDRegressor
model = ParallelPostFit(SGDRegressor(tol=1e-3,penalty="elasticnet",random_state=0))

X_cols_train = cols
del X_cols_train[0] #headers list of training data.

from dask_ml.model_selection import IncrementalSearchCV
search = IncrementalSearchCV(model, params, random_state=0)

search.fit(train_final[X_cols_train], train_final['target']) #X and y of training data
```
Thanks

Michael

**Comment by TomAugspurger** [comment]
See http://ml.dask.org/modules/generated/dask_ml.model_selection.IncrementalSearchCV.html#dask_ml.model_selection.IncrementalSearchCV, the `X` and `y` need to be dask arrays right now.

**Comment by MichaelSchroter** [comment]
Hi,

Thanks.

Michael

**Comment by MichaelSchroter** [comment]
Hi Tom,

I have redone as below,

```
X_cols_train = cols
del X_cols_train[0]

X = train_final[X_cols_train].values #create dask array from dask dataframe
y = train_final['target'].values #create dask array from dask dataframe

from dask_ml.wrappers import ParallelPostFit
params = {'estimator__alpha': np.logspace(-2, 1, num=1000),'estimator__l1_ratio': np.linspace(0, 1, num=1000),'estimator__average': [True, False]}

from sklearn.linear_model import SGDRegressor
model = ParallelPostFit(SGDRegressor(tol=1e-3,penalty="elasticnet",random_state=0))

from dask_ml.model_selection import IncrementalSearchCV
search = IncrementalSearchCV(model, params, random_state=0)

search.fit(X, y)
```

Output:
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-76-4d29271945bd> in <module>
----> 1 search.fit(X, y)

~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in fit(self, X, y, **fit_params)
    572             Additional partial fit keyword arguments for the estimator.
    573         """
--> 574         return default_client().sync(self._fit, X, y, **fit_params)
    575 
    576     @if_delegate_has_method(delegate=("best_estimator_", "estimator"))

~/env/lib/python3.5/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    671             return future
    672         else:
--> 673             return sync(self.loop, func, *args, **kwargs)
    674 
    675     def __repr__(self):

~/env/lib/python3.5/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

~/env/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/env/lib/python3.5/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/usr/lib/python3.5/asyncio/futures.py in result(self)
    291             self._tb_logger = None
    292         if self._exception is not None:
--> 293             raise self._exception
    294         return self._result
    295 

~/env/lib/python3.5/site-packages/tornado/gen.py in wrapper(*args, **kwargs)
    324                 try:
    325                     orig_stack_contexts = stack_context._state.contexts
--> 326                     yielded = next(result)
    327                     if stack_context._state.contexts is not orig_stack_contexts:
    328                         yielded = _create_future()

~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in _fit(self, X, y, **fit_params)
    522     @gen.coroutine
    523     def _fit(self, X, y, **fit_params):
--> 524         X, y = self._check_array(X, y)
    525 
    526         X_train, X_test, y_train, y_test = self._get_train_test_split(X, y)

~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in _check_array(self, X, y, **kwargs)
    437         if isinstance(y, np.ndarray):
    438             y = da.from_array(y, y.shape)
--> 439         X = check_array(X, **kwargs)
    440         kwargs["ensure_2d"] = False
    441         y = check_array(y, **kwargs)

~/env/lib/python3.5/site-packages/dask_ml/utils.py in check_array(array, *args, **kwargs)
    124             if np.isnan(array.shape[0]):
    125                 raise TypeError(
--> 126                     "Cannot operate on Dask array with unknown chunk sizes."
    127                 )
    128         if not accept_multiple_blocks and array.ndim > 1:

TypeError: Cannot operate on Dask array with unknown chunk sizes.
```

Would you be able to let me know what needs to be done to eliminate the error.

Thanks

Michael

**Comment by jjerphan** [comment]
As for:
```
TypeError: Cannot operate on Dask array with unknown chunk sizes.
```

This is because your are using Dask Arrays that do not have their informations about chunks size and shape when they are extracted as intended via `values` on a DataFrame.

As indicated by @TomAugspurger, the only way to manage this for now is to use numpy arrays.

Hence, *if you are sure that your dataset can fit into your memory*, you can try:
```python
X_cols_train = cols
del X_cols_train[0]

# Create Dask Array from Dask DataFrame and compute them to obtain numpy array
X = train_final[X_cols_train].values.compute()
y = train_final['target'].values.compute()

from dask_ml.wrappers import ParallelPostFit
params = {'estimator__alpha': np.logspace(-2, 1, num=1000),'estimator__l1_ratio': np.linspace(0, 1, num=1000),'estimator__average': [True, False]}

from sklearn.linear_model import SGDRegressor
model = ParallelPostFit(SGDRegressor(tol=1e-3,penalty="elasticnet",random_state=0))

from dask_ml.model_selection import IncrementalSearchCV
search = IncrementalSearchCV(model, params, random_state=0)

search.fit(X, y)
```

@TomAugspurger : I am facing the same problem when using `daskml.cluster.Kmeans` on Dask Arrays that originate from Dask Dataframe — because`values` do not update their `chunksize`s : do you think that this is easily fixable? I am inspecting it now.

**Comment by jjerphan** [comment]
Alternatively, you can use `.to_dask_array(lenghts=True)` instead of `.values.compute()` to get a dask array but with chunks information in it — and this may be a better practice.

**Comment by MichaelSchroter** [comment]
dask/dask#4518

**Comment by atyamsriharsha** [comment]
> Hi All,
> 
> I have created the training set for machine learning and when trying to `fit` model it gives a value error.
> 
> The code and error is as follows.
> 
> Code:
> 
> `search.fit(train_final[X_cols_train], train_final['target'])`
> 
> output:
> 
> ```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-105-9dea7c488bbf> in <module>
> ----> 1 search.fit(train_final[X_cols_train], train_final['target'])
> 
> ~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in fit(self, X, y, **fit_params)
>     572             Additional partial fit keyword arguments for the estimator.
>     573         """
> --> 574         return default_client().sync(self._fit, X, y, **fit_params)
>     575 
>     576     @if_delegate_has_method(delegate=("best_estimator_", "estimator"))
> 
> ~/env/lib/python3.5/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
>     671             return future
>     672         else:
> --> 673             return sync(self.loop, func, *args, **kwargs)
>     674 
>     675     def __repr__(self):
> 
> ~/env/lib/python3.5/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
>     275             e.wait(10)
>     276     if error[0]:
> --> 277         six.reraise(*error[0])
>     278     else:
>     279         return result[0]
> 
> ~/env/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
>     691             if value.__traceback__ is not tb:
>     692                 raise value.with_traceback(tb)
> --> 693             raise value
>     694         finally:
>     695             value = None
> 
> ~/env/lib/python3.5/site-packages/distributed/utils.py in f()
>     260             if timeout is not None:
>     261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
> --> 262             result[0] = yield future
>     263         except Exception as exc:
>     264             error[0] = sys.exc_info()
> 
> ~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
>    1131 
>    1132                     try:
> -> 1133                         value = future.result()
>    1134                     except Exception:
>    1135                         self.had_exception = True
> 
> /usr/lib/python3.5/asyncio/futures.py in result(self)
>     291             self._tb_logger = None
>     292         if self._exception is not None:
> --> 293             raise self._exception
>     294         return self._result
>     295 
> 
> ~/env/lib/python3.5/site-packages/tornado/gen.py in wrapper(*args, **kwargs)
>     324                 try:
>     325                     orig_stack_contexts = stack_context._state.contexts
> --> 326                     yielded = next(result)
>     327                     if stack_context._state.contexts is not orig_stack_contexts:
>     328                         yielded = _create_future()
> 
> ~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in _fit(self, X, y, **fit_params)
>     522     @gen.coroutine
>     523     def _fit(self, X, y, **fit_params):
> --> 524         X, y = self._check_array(X, y)
>     525 
>     526         X_train, X_test, y_train, y_test = self._get_train_test_split(X, y)
> 
> ~/env/lib/python3.5/site-packages/dask_ml/model_selection/_incremental.py in _check_array(self, X, y, **kwargs)
>     437         if isinstance(y, np.ndarray):
>     438             y = da.from_array(y, y.shape)
> --> 439         X = check_array(X, **kwargs)
>     440         kwargs["ensure_2d"] = False
>     441         y = check_array(y, **kwargs)
> 
> ~/env/lib/python3.5/site-packages/dask_ml/utils.py in check_array(array, *args, **kwargs)
>     149     elif isinstance(array, dd.DataFrame):
>     150         if not accept_dask_dataframe:
> --> 151             raise TypeError("This estimator does not support dask dataframes.")
>     152         # TODO: sample?
>     153         return array
> 
> TypeError: This estimator does not support dask dataframes.
> ```
> Also I would like to know when fitting data do we need to re-code string values in columns (in categorical data) to numerical data. For example if there is a column with categories `a,b,c` do we have to re-code it as for example as `1,2,3`. Furthermore if we need to do so then how do we make sure that the test set also is re-coded in the same pattern such as 1 for a and 2 for b.
> 
> Thank you
> 
> Michael

To make sure that the test set is also encoded in the same way as the train set we ideally fit the label encoder on test and train data combined and then transform the data in test and train separately. Hope this helps

**Comment by MichaelSchroter** [comment]
Thanks That helped
