### ISSUE TITLE
Error importing "IncrementalSearchCV"

### ISSUE THREAD

**Issue by tanayag** [dask/dask-ml#464]
```
>>> from dask_ml.model_selection import IncrementalSearchCV
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'IncrementalSearchCV'
```
When I am importing IncrementalSearchCV this is the error, and there is no traceback to track the problem!

**Comment by tanayag** [comment]
went into this file:
`https://github.com/dask/dask-ml/blob/master/dask_ml/model_selection/__init__.py`

removed the exception and then got to know that `dask distributed` is not installed

**Comment by stsievert** [comment]
Errors shouldn't pass silently, and shouldn't require reading the source.

This issue would probably be resolved with a dummy class in the try/except block in `model_selection/__init__.py`.

**Comment by TomAugspurger** [comment]
It'd be best to re-raise the import error with an informative message
saying that incremental search requires distributed.

**Comment by tanayag** [comment]
Created a pull, it should show the exact traceback, hence I put it with other hyper-parameter tuning algorithms
