### ISSUE TITLE
Support for scikit-optimize

### ISSUE THREAD

**Issue by Blusea** [dask/dask-ml#475]
scikit-optimize (https://github.com/scikit-optimize/scikit-optimize) supports the apis
sklearn.externals.joblib.{Parallel, delayed}

**Comment by TomAugspurger** [comment]
Can you give an example of what supporting scikit-optimize would look like?

Does this differ from https://github.com/dask/dask-ml/issues/300?

**Comment by TomAugspurger** [comment]
@Blusea any response to https://github.com/dask/dask-ml/issues/475#issuecomment-468263198?
