### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by MichaelSchroter** [dask/dask-ml#478]
Hi All,

There is a link that does not open in [dask-ml](https://ml.dask.org/modules/generated/dask_ml.wrappers.Incremental.html#dask_ml.wrappers.Incremental) docs pages. In the page the [list of incremental learners](https://scikit-learn.org/stable/modules/scaling_strategies.html#incremental-learning#noqa) is broken. 

Would anyone be able to fix it

Thanks

Michael

**Comment by TomAugspurger** [comment]
Can you put up a PR with a fix?

**Comment by TomAugspurger** [comment]
Closed by #483
