### ISSUE TITLE
Tests are Failing after installation 

### ISSUE THREAD

**Issue by atyamsriharsha** [dask/dask-ml#482]
After I followed the steps as given in the http://ml.dask.org/contributing.html, there are some tests which are failing after I execute the pytest tests/preprocessing . I am attaching the report for reference. Is the behaviour expected or did I miss a major step in setting up the module.
![dask_test_error](https://user-images.githubusercontent.com/10818570/54242585-6471fb80-44e2-11e9-8f18-7f3008343169.png)

**Comment by jrbourbeau** [comment]
Thanks for reporting @atyamsriharsha! What version of `dask-ml` are you using? There were some recent commits to `master` that fixed several test failures

**Comment by atyamsriharsha** [comment]
Hey, @jrbourbeau  thanks for reverting back quickly. I am attaching a picture for reference 
![dask-ml_version](https://user-images.githubusercontent.com/10818570/54243153-8bc9c800-44e4-11e9-9607-7f018281a0d1.png)

**Comment by jrbourbeau** [comment]
I'm not able to reproduce these test failures on the current `dask-ml` `master` branch. Could you verify that you're using an up-to-date `master` branch? The output of `git rev-parse HEAD` should be `d68c7fa9dbfac2b037a0caf5b4feb4940efa6a2c` in this case

**Comment by atyamsriharsha** [comment]
Hello, @jrbourbeau when I try to create a conda environment the error shows up as follows and I think the error lies at this stage as I  am using up to date master branch. Do I need to install these packages manually using conda? and by the way, I have already xgboost installed and I am using python version 
3.6.5. Do I need to upgrade my python or am I doing something wrong in the installation? Thank you :)

![dask_env_error](https://user-images.githubusercontent.com/10818570/54305845-57f2af00-4585-11e9-8382-2c7cf920531d.png)

**Comment by jrbourbeau** [comment]
Hmm after some investigating, it appears that `xgboost` on conda-forge doesn't support Windows and the corresponding package is called `py-xgboost` on the `defaults` channel. The `nomkl` package is not required (and potentially also not available on Windows?)

Sorry about this, we should improve the installation instructions for Windows users. However, a quick sub-optimal fix would be to install the packages in `ci/environment-3.6.yml` other than `nomkl` and `xgboost` (since you already have `xgboost` installed)

**Comment by atyamsriharsha** [comment]
@jrbourbeau I skipped the xgboost and nomkl packages in ci/environment-3.6.yml and the environment was created successfully but after running pytest tests/preprocessing I am getting same assertion error when comparing data types in all the failures 
![assertion_error](https://user-images.githubusercontent.com/10818570/54337210-768b9100-45eb-11e9-9fe8-8aff72db0395.png)

**Comment by TomAugspurger** [comment]
Those assertions should be made platform-independent. Something like `assert ten['D'].dtype == np.dtype("int64")`.

May be time to setup windows CI on azure. I won't have time in the next couple days, but hopefully soon.
