### ISSUE TITLE
train_test_split documentation

### ISSUE THREAD

**Issue by r0f1** [dask/dask-ml#490]
Hi,
The documentation on [this page](https://dask-ml.readthedocs.io/en/latest/modules/generated/dask_ml.model_selection.train_test_split.html) has several issues. The arguments unter `dask_ml.model_selection.train_test_split` are not properly formatted, there are spelling mistakes (defualt instead of default), and the first two lines of the last code example are also not properly formatted. I tried to submit a pull request via clicking on the "Edit on GitHub" link at the top right corner of the page, but the button is also broken and leading me to a 404 error.

Would be nice, if someone could tell me how to fix this documentation page.
Best, Flo

**Comment by TomAugspurger** [comment]
The docs are at http://ml.dask.org/modules/generated/dask_ml.model_selection.train_test_split.html now.

That has a contributing guide.

**Comment by r0f1** [comment]
Ok, I've created a pull request. Thanks.

**Comment by TomAugspurger** [comment]
Thanks! This will be closed automatically when your PR is merged.
