### ISSUE TITLE
LabelEncoder returning dask array when passing dask Series

### ISSUE THREAD

**Issue by henriqueribeiro** [dask/dask-ml#492]
Example:

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd
from dask_ml.preprocessing import LabelEncoder

def generate_df(size):
    d = {'categorical': np.random.choice(['A', 'B', 'C'], size=size)}

    df = pd.DataFrame(d, dtype='category')
    ddf = dd.from_pandas(df, 2)
    return df, ddf

df, ddf = generate_df(10)
uniques = pd.DataFrame(['A', 'B', 'C'], dtype='category')
enc = LabelEncoder().fit(uniques)
type(enc.transform(ddf['categorical']))
```
Output:
```
dask.array.core.Array
```

I believe it should return a dask Series right?

**Comment by stsievert** [comment]
Is this an issue? Scikit-Learn does the same thing:

``` python
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

df = pd.DataFrame({"categories": np.random.choice(["A", "B", "C"], size=10)}, dtype="category")

enc = LabelEncoder().fit(df)
enc.transform(df.categories)  # array([2, 1, 2, 0, 1, 0, 2, 1, 0, 0])
```

I put in a Pandas Series to `enc.transform` and got a NumPy array.

**Comment by henriqueribeiro** [comment]
True! The difference is that pandas column assignment support type Array while dask don't. So this would be a solution to simply assign the results of the transformation into a new dask column

**Comment by TomAugspurger** [comment]
I think this was deliberate to match the API behavior of scikit-learn. You could raise an issue there to see if Series can be preserved.

> True! The difference is that pandas column assignment support type Array while dask don't. So this would be a solution to simply assign the results of the transformation into a new dask column

To do that, you'd need to align the indices. Something like

```
trn = LabelEncoder().fit_transform(uniques)
df['trn'] = dd.from_dask_array(trn, index=df.index)
```

dask doesn't know that the blocks of the transformed array align with the partitions of the DataFrame.

**Comment by henriqueribeiro** [comment]
Thanks @TomAugspurger
