### ISSUE TITLE
model.score() returns MSE but the docstring states that it returns R2

### ISSUE THREAD

**Issue by daguito81** [dask/dask-ml#507]
In dask_ml linear_models LinearRegression. If you use model.score(X_test, y_test) then you get back the Mean Squared Error instead of the R2 which is how sklearn's implementation does it. 
On top of that the score method defined has a docstring that states that it returns the r2 score instead of the MSE. 

We can see in the code here https://github.com/dask/dask-ml/blob/e1b21e6dbcfae8341d05d39544ab90dce21fdb2b/dask_ml/linear_model/glm.py#L304-L328

That the docstring says r2 score, but the method returns the mean_squared_error from dask_ml.utils.

Either the docstring should be changed to reflect the real return value. Or the r2_score method should be defined and then use that on the rerturn statement of the score method

**Comment by TomAugspurger** [comment]
> Or the r2_score method should be defined and then use that on the rerturn statement of the score method

That sounds best to me. We have `dask_ml.metrics.r2_score`, so we should be able to fix this relatively easily. Are you interested in working on it?

**Comment by akoury** [comment]
@TomAugspurger the thing is that ```dask_ml.metrics.mean_squared_error```is not being used here, it comes from [dask-gml](https://github.com/dask/dask-glm/blob/master/dask_glm/utils.py) where there is currently no r2_score method to switch with, would that require adding it there or is it possible to just use ```dask_ml.metrics.r2_score```?

**Comment by daguito81** [comment]
The linear model was implemented 2 years ago and dask_ml metrics was implemented a year ago. So I'm guessing that's the reason why it's using dask-gml instead of the dask_ml.metrics  
I would assume that it would be better to start using dask_ml.metrics in the different models instead.

This could also raise the issue of going through the different model and implementing dask_ml.metrics instead of dask_glm.utils 

@TomAugspurger what do you think ?

**Comment by Juanlu001** [comment]
> or is it possible to just use dask_ml.metrics.r2_score?

As you said, I think it should be enough to replace `dask_glm.utils.mean_squared_error` with `dask_ml.metrics.r2_score`, even if they don't come from the same package.

**Comment by TomAugspurger** [comment]
> This could also raise the issue of going through the different model and implementing dask_ml.metrics instead of dask_glm.utils

Yes, I think that's best.

**Comment by daguito81** [comment]
I can take care of this in the coming days @TomAugspurger. Should be simple enough to import and change the return statement. I can create a different issue for other dask-glm imports that could be changed to dask_ml.
