### ISSUE TITLE
GridsearchCV with prescattered data

### ISSUE THREAD

**Issue by quasiben** [dask/dask-ml#516]
During a recent debug session with @TomAugspurger we thought that dask-ml could take advantage of data which was pre-scattered:

> client.scatter(data, broadcast=True)

Current understanding is that dask-ml will not take advantage of pre-scatter data as the call to `KFold` will chop up data and not see the cached data on the workers.

**Comment by TomAugspurger** [comment]
Looking at these, I notice we have a different prefix.

```python
from distributed import Client
import dask_ml.model_selection
import numpy as np
from sklearn import svm, datasets

client = Client()
client

iris = datasets.load_iris()

parameters = {'kernel': ['linear', 'rbf'], 'C': [1, 10]}
svc = svm.SVC()
clf = dask_ml.model_selection.GridSearchCV(svc, parameters)

xx = client.scatter(iris.data, broadcast=True)
yy = client.scatter(iris.target, broadcast=True)

clf.fit(iris.data, iris.target)

key = list(clf.dask_graph_)[2]
print(clf.dask_graph_[key])
print(xx.key)
```

```
(<function dask_ml.model_selection.methods.cv_split(cv, X, y, groups, is_pairwise, cache)>,
 StratifiedKFold(n_splits=3, random_state=None, shuffle=False),
 'array-b44c3d00069ed183d60844351ba8bd54',
 'array-b87288d64805cff577d3bfad8f4d5829',
 None,
 False,
 True)
'ndarray-b44c3d00069ed183d60844351ba8bd54'
```


So we have `ndarray-<token>` for the scatter (from dask / distributed), and `array-<token>` for the version built by dask-ml.

**Comment by lwj5** [comment]
I would like to see this as well. dask-ml should scatter data after kfold.

**Comment by lwj5** [comment]
I won't be able to work on this now, but if this is not closed by the end of Oct, I'll take a look at this.
