### ISSUE TITLE
xgbclassifier gives error with gridsearchcv and dask dataframes

### ISSUE THREAD

**Issue by sandys** [dask/dask-ml#521]
```
import dask.dataframe as dd
import numpy as np
import pandas as pd
from dask_ml.model_selection import GridSearchCV
from dask_ml.xgboost import XGBClassifier
from distributed import Client
from sklearn.datasets import load_iris

if __name__ == '__main__':

    client = Client()

    data = load_iris()

    x = pd.DataFrame(data=data['data'], columns=data['feature_names'])
    x = dd.from_pandas(x, npartitions=2)

    y = pd.Series(data['target'])
    y = dd.from_pandas(y, npartitions=2)

    estimator = XGBClassifier(objective='multi:softmax', num_class=4)
    grid_search = GridSearchCV(
        estimator,
        param_grid={
            'n_estimators': np.arange(15, 105, 15)
        },
        scheduler='threads'
    )

    grid_search.fit(x, y)
    results = pd.DataFrame(grid_search.cv_results_)
    print(results.to_string())
```

gives this

> Traceback (most recent call last):
>   File "d.py", line 30, in <module>
>     grid_search.fit(x, y)
>   File "/usr/local/lib/python3.7/site-packages/dask_ml/model_selection/_search.py", line 1233, in fit
>     cache_cv=self.cache_cv,
>   File "/usr/local/lib/python3.7/site-packages/dask_ml/model_selection/_search.py", line 203, in build_cv_graph
>     X_name, y_name, groups_name = to_keys(dsk, X, y, groups)
>   File "/usr/local/lib/python3.7/site-packages/dask_ml/model_selection/utils.py", line 85, in to_keys
>     assert not is_dask_collection(x)
> AssertionError
>

**Comment by TomAugspurger** [comment]
Does it work if you provide X and y as dask arrays?

**Comment by sandys** [comment]
I also saw this - https://github.com/vbonvin/malware-kaggle/blob/f213b50e63522da47c83c6238d236d0f2e05b2d4/dask_ml_2.ipynb 

similar struggles. I'm currently trying to wrap xgbclassifier in ParallelPostFit and still not working.

**Comment by TomAugspurger** [comment]
Those are dask data frames / series, not arrays.

This gets partway there

```
import dask.array as da
import dask.dataframe as dd
import numpy as np
import pandas as pd
from dask_ml.model_selection import GridSearchCV
from dask_ml.xgboost import XGBClassifier
from distributed import Client
from sklearn.datasets import load_iris

if __name__ == '__main__':

    client = Client()

    data = load_iris()
    x = da.from_array(data.data)
    y = da.from_array(data.target)

    estimator = XGBClassifier(objective='multi:softmax', num_class=4)
    grid_search = GridSearchCV(
        estimator,
        param_grid={
            'n_estimators': np.arange(15, 105, 15)
        },
        scheduler='threads'
    )

    grid_search.fit(x, y, classes=[0, 1, 2])
    results = pd.DataFrame(grid_search.cv_results_)
    print(results.to_string())
```

Then I think we run into https://github.com/dask/dask-xgboost/pull/28/files

```pytb
Traceback (most recent call last):
  File "foo.py", line 27, in <module>
    grid_search.fit(x, y, classes=[0, 1, 2])
  File "/Users/taugspurger/sandbox/dask-ml/dask_ml/model_selection/_search.py", line 1262, in fit
    out = scheduler(dsk, keys, num_workers=n_jobs)
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/Users/taugspurger/sandbox/dask-ml/dask_ml/model_selection/methods.py", line 318, in fit_and_score
    est_and_time = fit(est, X_train, y_train, error_score, fields, params, fit_params)
  File "/Users/taugspurger/sandbox/dask-ml/dask_ml/model_selection/methods.py", line 238, in fit
    est.fit(X, y, **fit_params)
  File "/Users/taugspurger/sandbox/dask-xgboost/dask_xgboost/core.py", line 351, in fit
    num_boost_round=self.n_estimators)
  File "/Users/taugspurger/sandbox/dask-xgboost/dask_xgboost/core.py", line 191, in train
    labels, dmatrix_kwargs, **kwargs)
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/distributed/client.py", line 753, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/distributed/utils.py", line 331, in sync
    six.reraise(*error[0])
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/distributed/utils.py", line 316, in f
    result[0] = yield future
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Users/taugspurger/miniconda3/envs/dask-xgboost/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/taugspurger/sandbox/dask-xgboost/dask_xgboost/core.py", line 111, in _train
    data_parts = data.to_delayed()
AttributeError: 'numpy.ndarray' object has no attribute 'to_delayed'
```

Just as an aside, I'm not sure using the threaded scheduler with GridSearchCV and a dask_xgboost.XGBClassifer makes sense. The dask-xgboost classifiers only work with the distributed scheduler. Is your dataset larger than RAM?

**Comment by sandys** [comment]
hi Tom,
thanks for your patience.
Sorry for the threaded scheduler, i tried to create a minimal example. 

in my own code, I used 

```
train_X = dd.from_pandas(train_X, npartitions=4).to_dask_array(lengths=True)
train_y = dd.from_pandas(train_y, npartitions=4).to_dask_array(lengths=True)
```

and yes, i hit this issue.
Another point is that i use a sklearn pipeline and converting to array, throws off the pipeline. i use a `dask_ml.compose.ColumnTransformer`, but it throws 

> ValueError('Specifying the columns using strings is only supported for pandas DataFrames')

I think the same thing happens in `sklearn.preprocessing.PolynomialFeatures`

**Comment by TomAugspurger** [comment]
I'm not sure about the column transformer issue. But it sounds like you
convert to an array, but are still trying to use column names for the
transformer? Once you have an array you can only use positions.

**Comment by sandys** [comment]
sure thing.
but i have tons of intermediate transformations and a lot of them are
indexing using column names (because the frame goes through lots of
renaming, dropping of columns, etc)

is there any way i can wrap the xgboost code so that it can take a
dataframe and still work ?

**Comment by TomAugspurger** [comment]
There are two components

1. Accept dask dataframes in GridSearchCV
2. Accept concrete ndarray / datafarme in dask-xgboost (https://github.com/dask/dask-xgboost/pull/28/files)


I've included a small example with the failure for 1, though I don't plan to work on it further. I'm not sure when the conversion from Dataframe should be done.

<details>

```python
import pandas as pd
import numpy as np
import dask.array as da
import dask.dataframe as dd

import sklearn.linear_model
import sklearn.datasets
import sklearn.model_selection
import dask_ml.model_selection

iris = sklearn.datasets.load_iris()
X = iris.data
y = iris.target


df = pd.DataFrame(X)
ddf = dd.from_pandas(df, 2)

dy = pd.Series(y)
ddy = dd.from_pandas(dy, 2)

clf = sklearn.linear_model.LogisticRegression(multi_class="auto", solver="lbfgs", max_iter=200)

param_grid = {'C': [0.1, 1, 10]}
a = sklearn.model_selection.GridSearchCV(clf, param_grid, cv=5)
b = dask_ml.model_selection.GridSearchCV(clf, param_grid, cv=5)
a.fit(X, y)

a.fit(df, dy)

b.fit(ddf, ddy)
```

</details>

**Comment by xiaozhongtian** [comment]
@TomAugspurger
Hello,
I have met the same problem here that is exactly what you summarized above.
Dask dataframes should be accepted in GridSearchCV. 
It's really important to have a complete chain with this component. I have re-implement some estimators of sklearn for dask dataframe and I found that It has a great problmem that it's not supported by the dask dataframe in GridSearch with the pipeline of these estimaors.

**Comment by TomAugspurger** [comment]
@xiaozhongtian are you interested in working on it?

**Comment by sandys** [comment]
Hi Tom
Could you give a hint on the approach we should take in case we would like
to fix it ?

I don't know if I can, but i can take a shot

**Comment by TomAugspurger** [comment]
For the first item from https://github.com/dask/dask-ml/issues/521#issuecomment-504578653, the first step would be to update https://github.com/dask/dask-ml/blob/0db2e5fbf2dfab1a3bd8f924d002b7bae96f1e76/dask_ml/model_selection/utils.py#L73 to handle dask data frames. I'm assuming there will be other issues that need to be resolved after that's handled.

**Comment by xiaozhongtian** [comment]
Hello @TomAugspurger 
I have read the source code for this part. It has some functions like build the graph or cv_graph that makes me a little confusing. Maybe I need to understand how to build the dask graph for fixing this. 
In addition, I have many works to do recently. I can't assure the progress of this work.

**Comment by ericmjl** [comment]
Will any of you be at the SciPy conference? @TomAugspurger, will there be a sprint for dask-ml?

**Comment by TomAugspurger** [comment]
I won't be. I know that @mrocklin and @jrbourbeau will be around, and they're hosting a Dask sprint: https://github.com/dask/dask/issues/4639

**Comment by mrocklin** [comment]
@stsievert , who works on dask-ml a bit, will also be around.

**Comment by stsievert** [comment]
I'll be around for the first couple days of the conference (regrettably not Friday or the sprints).

**Comment by Casyfill** [comment]
Missed the conference but would love to help - stumbled upon the same issue.

**Comment by sandys** [comment]
hi guys - any update on this part ? we would love to be able to use this

**Comment by mmccarty** [comment]
I'll take a look. I've actually ran into this issue as well.

**Comment by mmccarty** [comment]
Opened a PR (#612) that implements @TomAugspurger's suggestion. Surely there's more.

**Comment by sandys** [comment]
Thanks for doing this. This is the only blocker from moving to Dask from
Sagemaker.

Most training code has sklearn pipeline transforms for data.
I'm not familiar with Dask internals, but I can get my team to test out
whatever you guys do.

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask-ml/pull/612 is in now, if people want to try it out and report back how it works. On the surface, things seem OK.

**Comment by Abmasha** [comment]
Hi guys , I facing the same attribute error when I am trying to pass the daskml grid search , did anyone has the solution?

**Comment by TomAugspurger** [comment]
@Abmasha can you open a new issue with a minimal example and your versions of dask-ml & xgboost?

**Comment by Abmasha** [comment]
Hi Tom , I am using light GBM with the Dask grid   search, data is huge so no option left except using Dask with joblib for parallel and l  am getting the same error.

**Comment by TomAugspurger** [comment]
Could you open a new issue with a minimal example?
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by Sajjad1989** [comment]
Yes just did it thanks
