### ISSUE TITLE
PolynomialFeatures does not preserve index

### ISSUE THREAD

**Issue by jtilly** [dask/dask-ml#562]
When using the `PolynomialFeatures` transformer with `preserve_dataframe=True`, we lose the index of the data frame. 

```python
import pandas as pd
from dask_ml.preprocessing import PolynomialFeatures

df = pd.DataFrame({"x": [1, 2]}, index=[2, 3])
PolynomialFeatures(degree=1, preserve_dataframe=True).fit_transform(df)
#>     1    x
#>0  1.0  1.0
#>1  1.0  2.0
```

The correct output should be
```python
#>     1    x
#>2  1.0  1.0
#>3  1.0  2.0
```

Same problem occurs with dask data frames.

To fix this, I would like to add `index=X.index` to
https://github.com/dask/dask-ml/blob/17568750c85c2cbc3c41b22a4b3498006cd0ed67/dask_ml/preprocessing/data.py#L993
and 
https://github.com/dask/dask-ml/blob/17568750c85c2cbc3c41b22a4b3498006cd0ed67/dask_ml/preprocessing/data.py#L998

Happy to send the PR. Just want to make sure I'm not missing anything or that there's a reason for the current behavior.

**Comment by TomAugspurger** [comment]
Thanks for the report.  Your proposed changes sound exactly correct.
