### ISSUE TITLE
Contributing docs doesn't include method to build docs

### ISSUE THREAD

**Issue by stsievert** [dask/dask-ml#564]
I followed the guidelines at https://ml.dask.org/contributing.html:

```
$ conda env create -f ci/environment-3.7.yaml --name=dask-ml-dev
$ python -m pip install -e ".[dev]"
```

This worked. I made some documentation changes, so I had to build the docs. Typing `make html` in the `docs/` directory yielded some errors, and I had to install extra packages:

```
$ cd docs
$ make html
$  pip install IPython
$ make html
$ pip install jupyter_client
```

**Comment by TomAugspurger** [comment]
Sorry about that. You can use the env `ci/environment-docs.yaml`, which should have everything necessary.
