### ISSUE TITLE
ColumnTransformer is broken in Version 1.1.0 wheel on pypi

### ISSUE THREAD

**Issue by fdion** [dask/dask-ml#575]
There is an issue with the wheel archive of dask_ml version 1.1.0, found on pypi:

[dask_ml-1.1.0-py3-none-any.whl](https://files.pythonhosted.org/packages/52/c7/c69664dd30c8da1275e23bda3e00d9d1b3244ac9cc6527d0e804a8ea5758/dask_ml-1.1.0-py3-none-any.whl)

Github and the tar.gz archive of v.1.1.0 are ok. ColumnTransformer inherits from a class that exists:

[_column_transformer.py#L12](https://github.com/dask/dask-ml/blob/master/dask_ml/compose/_column_transformer.py#L12)

But the wheel file has this on line 12 of the _column_transformer.py file:

`class ColumnTransformer(sklearn.compose.ColumnTrasformer):`

It should say `sklearn.compose.ColumnTransformer`. It is missing the n.

**Comment by TomAugspurger** [comment]
Thanks for the report. I'm not sure what happened, but I must have had that file open in an editor window when I ran `setup.py bdist_wheel`. Just released 1.1.1 with a fixed version.
