### ISSUE TITLE
Mac 10.15 Assertion failed

### ISSUE THREAD

**Issue by tinyms** [dask/dask-ml#576]
when `from dask_ml.cluster import KMeans` and run throw:

Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.

**Comment by stsievert** [comment]
Could you craft a minimal working example? I'm not sure how to reproduce this error; `from dask_ml.cluster import KMeans` runs fine on my machine with my setup (macOS 10.14.6). http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

This might be relevant: https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/

**Comment by tinyms** [comment]
**When import is thrown an error, annotating it becomes normal**

```
from AnyQt.QtCore import Qt
from Orange.widgets import widget, gui
from Orange.widgets.settings import Setting
from Orange.widgets.utils.widgetpreview import WidgetPreview
from Orange.widgets.widget import Input, Output

from autolearn import adapter
# from dask_ml.cluster import KMeans


class DaskKMeans(widget.OWWidget):
    name = "k-Means 聚类"
    description = "基于轮廓质量估计的k均值聚类算法"
    icon = "icons/KMeans.svg"
    priority = 2100
    keywords = ["kmeans", "clustering"]

    class Inputs:
        data = Input("数据", adapter.Table)

    class Outputs:
        centroids = Output("聚类数据", adapter.Table)

    resizing_enabled = False
    buttons_area_orientation = Qt.Vertical

    want_main_area = False
    max_clusters = Setting(8)
    auto_commit = Setting(True)

    def __init__(self):
        super().__init__()

        self.data = None

        vbox = gui.vBox(self.controlArea, box="最大聚类数")
        self.max_cluster_box = gui.spin(vbox, self, 'max_clusters', minv=2, maxv=30, step=1)
        gui.widgetLabel(vbox, '最大特征')
        # vbox.layout().addWidget(self.max_cluster_box)

        self.apply_button = gui.auto_commit(
            self.buttonsArea, self, "auto_commit", "应用", box=None,
            commit=self.commit)
        gui.rubber(self.controlArea)

    @Inputs.data
    def set_data(self, data):
        # self.data, old_data = data, self.data
        # framework.kmeans(self.data.dataframe)
        pass

    def commit(self):
        pass


if __name__ == "__main__":  # pragma: no cover
    WidgetPreview(DaskKMeans).run()

```

**Comment by tinyms** [comment]
I created a demo.py file, just wrote a line of code ``from dask_ml.cluster import KMeans``, and then ran, the same error occurred.

**Comment by stsievert** [comment]
>  just wrote a line of code `from dask_ml.cluster import KMeans`

Same here, and I can reproduce on my machine.

``` python
from dask_ml.cluster import KMeans
```

throws the same error on macOS 10.14.6 and Dask-ML (versions 1.0.0 and 1.1.1):

```
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.
[1]    73570 abort      ipython
```

This is the same issue as https://github.com/dask/dask/issues/5215. In https://github.com/numba/numba/issues/4256#issuecomment-546860012, apparently import order solves this issue?

**Comment by stsievert** [comment]
See https://github.com/dask/dask-ml/pull/577

**Comment by tinyms** [comment]
Install pyarrow==0.12.1 and run without errors, expect pyarrow 0.15.1 release
