### ISSUE TITLE
dask-searchcv mentioned in dask-ml docs

### ISSUE THREAD

**Issue by lebedov** [dask/dask-ml#585]
It appears that dask-searchcv is still explicitly mentioned in some parts of the dask-ml documentation (e.g., [here](https://github.com/dask/dask-ml/blame/master/docs/source/hyper-parameter-search.rst#L57)) despite having been merged.

**Comment by TomAugspurger** [comment]
Thanks for pointing that out. Those should all be updated.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/dask/dask-ml/pull/586
