### ISSUE TITLE
Included conda environment is not suitable on a Mac

### ISSUE THREAD

**Issue by datajanko** [dask/dask-ml#587]
Hey, I just wanted to use the provided conda environment file and found several issues:

Firstly, not all dependencies are installed on a Mac:
```
ImportError while loading conftest '/Users/jankoch/Projects/own/dask-ml/tests/conftest.py'.
tests/conftest.py:4: in <module>
    import dask.dataframe as dd
//miniconda3/envs/dask-ml-dev/lib/python3.6/site-packages/dask/dataframe/__init__.py:55: in <module>
    raise ImportError(str(e) + "\n\n" + msg)
E   ImportError: fsspec is required to use any file-system functionality. Please install using
E   conda install -c conda-forge 'fsspec>=0.3.3'
E   or
E   pip install 'fsspec>=0.3.3'
E
E   Dask dataframe requirements are not installed.
E
E   Please either conda or pip install as follows:
E
E     conda install dask                     # either conda install
E     pip install dask[dataframe] --upgrade  # or pip install
```

secondly, when trying to install pre-commit (which occasionally is better to install via conda). A lot of packages need to be updated.

Is anybody having similar experiences?

**Comment by TomAugspurger** [comment]
Which environment file are you using? The ones in `ci` are primarily intended for the test and doc builds.

I'm surprised to see the fsspec import error, given that `dask` is in those environment files.

**Comment by datajanko** [comment]
My bad, my fork was still lagging heavily behind and I just did not realize this. Sorry
