### ISSUE TITLE
Is `nearest_neighbors` available in spectral clustering?

### ISSUE THREAD

**Issue by yl-1993** [dask/dask-ml#593]
In the [document of spectral clustering](https://github.com/dask/dask-ml/blob/92aca8c2166912d0ca80d118628f47ba943779c6/dask_ml/cluster/spectral.py#L53), it states to support `nearest_neighbors' and 'precomputed'. But it seems that the spectral clustering actually supports [these four metrics](https://github.com/dask/dask-ml/blob/92aca8c2166912d0ca80d118628f47ba943779c6/dask_ml/metrics/pairwise.py#L155).

**Comment by TomAugspurger** [comment]
Yes, probably a copy-paste error from the scikit-learn docs. A fix to
correct the docs / implement the other kernels / nearest neighbors would be
welcome (though
nearest neighbors may take quite a bit of work).

**Comment by yl-1993** [comment]
Thanks. I create a PR https://github.com/dask/dask-ml/pull/594 to correct the docs for now.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/dask/dask-ml/pull/594
