### ISSUE TITLE
import dask_ml.cluster raises a ModuleNotFoundError from sklearn

### ISSUE THREAD

**Issue by petermorrow** [dask/dask-ml#597]
```
$ pip install dask-ml
$ python
>>> import dask_ml.cluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peter/.virtualenvs/DASK/lib/python3.7/site-packages/dask_ml/cluster/__init__.py", line 3, in <module>
    from .k_means import KMeans  # noqa
  File "/Users/peter/.virtualenvs/DASK/lib/python3.7/site-packages/dask_ml/cluster/k_means.py", line 23, in <module>
    from ._compat import _k_init
  File "/Users/peter/.virtualenvs/DASK/lib/python3.7/site-packages/dask_ml/cluster/_compat.py", line 4, in <module>
    from sklearn.cluster._k_means import _k_init
ModuleNotFoundError: No module named 'sklearn.cluster._k_means'
>>>
```

It looks like this issue is related to the latest version of scikit-learn deprecating that module, because installing with the previous version of scikit-learn works.

```
$ pip install dask-ml==1.1.1 scikit-learn==0.21.*
$ python
>>> import dask_ml.cluster
>>>
```

**Comment by TomAugspurger** [comment]
Does it work with dask-ml master? I restructured a few things to avoid
warnings, but I don't recall if they've been released yet.

**Comment by petermorrow** [comment]
Doesn't looks like it. I tried installing master and got the same issue.
```
$ pip install git+https://github.com/dask/dask-ml.git
$ pip freeze | grep scikit-learn
scikit-learn==0.22.1
```
I think it has to do with [this dependency](https://github.com/dask/dask-ml/blob/master/setup.py#L19) -changing it from `scikit-learn>=0.21` to `scikit-learn==0.21` might do the trick.

**Comment by TomAugspurger** [comment]
We don't want to pin an exact version of scikit-learn. We'd rather update
things to be compatible.

I would gladly accept a PR to fix things, otherwise I'll be able to look at
it in a few days.

**Comment by petermorrow** [comment]
I can take a stab at a PR.

In the `dask_ml.cluster._compat` module there is this import logic:
```
if SK_022:
    from sklearn.cluster._k_means import _k_init
else:
    from sklearn.cluster.k_means_ import _k_init
```

Changing it to always import `_k_init` from `sklean.cluster.k_means_` doesn't raise a `ModuleNotFoundError` but yields a `FutureWarning`.

> The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.

I could submit a PR to always import from `sklearn.cluster.k_means_`, but that's probably not a good long term solution.

Or I could look into changing the `dask_ml.cluster.k_means.init_pp` function's implementation to use scikit-learn's public api. Not sure what this entails but I assume that you're using `_k_init` from the private scikit-learn API because there weren't any good options in the public API.

What approach do you think is best right now?

**Comment by TomAugspurger** [comment]
Thanks for looking into this.

Just importing from sklearn.cluster.k_means_ likely won't pass CI. That
will cause warnings which will cause the tests to fail.

I would need to look more closely to say for sure. If init_pp is available
via the public API that'd be best.

**Comment by TomAugspurger** [comment]
Looking into this now.

**Comment by gustavomrg** [comment]
```ImportError                               Traceback (most recent call last)
<ipython-input-48-d46ea042c026> in <module>
     12 import umap.plot
     13 import matplotlib.pyplot as plt
---> 14 import dask_ml.cluster

/project/libs/lib/python3.6/site-packages/dask_ml/cluster/__init__.py in <module>
      1 """Unsupervised Clustering Algorithms"""
      2 
----> 3 from .k_means import KMeans  # noqa
      4 from .spectral import SpectralClustering  # noqa

/project/libs/lib/python3.6/site-packages/dask_ml/cluster/k_means.py in <module>
     20 )
     21 from ..utils import _timed, _timer, check_array, row_norms
---> 22 from ._compat import _k_init
     23 
     24 import numba  # isort:skip (see https://github.com/dask/dask-ml/pull/577)

/project/libs/lib/python3.6/site-packages/dask_ml/cluster/_compat.py in <module>
----> 1 from sklearn.cluster._kmeans import _k_init
      2 
      3 __all__ = ["_k_init"]

ImportError: cannot import name '_k_init'
 ```

I am using python 3.6, dask-ml-1.7.0 and scikit-learn-0.23.2
