### ISSUE TITLE
Add mild type annotations

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ml#607]
I'm looking through the model selection code and I find myself curious what the various inputs and outputs are to functions.  This might be a bit of our codebase that could use with some mild type annotations.  

This might be a good activity for someone who wanted to become familiar with the Dask-ML codebase.

**Comment by dhirschfeld** [comment]
I find type annotations hugely helpful to understand the intended interface/behaviour of a function

**Comment by TomAugspurger** [comment]
Sounds good to me.

**Comment by prasunanand** [comment]
Hi, 
I would like to work on this issue.

**Comment by jakirkham** [comment]
Please feel free. My guess is people here would be happy to help review a PR 🙂

**Comment by prasunanand** [comment]
How should I declare the type signature of `array-like` ?

**Comment by TomAugspurger** [comment]
I'd follow pandas' definitions:
https://github.com/pandas-dev/pandas/blob/master/pandas/_typing.py

with the addition of Dask Arrays / DataFrames where appropriate.

**Comment by prasunanand** [comment]
Thanks @TomAugspurger :)
