### ISSUE TITLE
disambiguation between xgboost.dask vs dask-ml xgboost

### ISSUE THREAD

**Issue by sandys** [dask/dask-ml#618]
The recent 1.0.0 release of xgboost brings the xgboost.dask interface .
A relevant example is here - https://github.com/dmlc/xgboost/blob/master/demo/dask/sklearn_cpu_training.py

the related documentation is here - https://xgboost.readthedocs.io/en/latest/tutorials/dask.html

there are intertwined usecases - e.g. xgb.dask.DaskDMatrix vs the work being done in https://github.com/dask/dask-ml/issues/605 

How do you see both these projects co-existing ? will one subsume the other ? we are currently on dask-ml and wondering which direction to go in.

**Comment by TomAugspurger** [comment]
See https://github.com/dask/dask-xgboost/issues/39.

My thoughts are at https://github.com/dask/dask-xgboost/issues/39#issuecomment-562324378.

**Comment by TomAugspurger** [comment]
Let's keep the discussion on dask-xgboost vs. xgboost over there, if you have more to add.

Work like https://github.com/dask/dask-ml/issues/605 will of course have to be done here.
