### ISSUE TITLE
SearchCV: memory issues on workers

### ISSUE THREAD

**Issue by IanQS** [dask/dask-ml#621]
Hey all! 
 
# Scenario

Say I have 50 workers and the number of combinations of parameters from doing my `SearchCV` is also 50. My workers are dying out and it SEEMS like only 30 or 40 of them are getting "saturated" while the rest sit idly.

# My hypothesis

This makes me think that some workers are being made to do multiple training jobs since, in theory, a single "dataset" on the worker shouldn't cause an error but if it were to double in size, it would. 

# Questions

If my hypothesis is correct is it possible to schedule it via something like [dask worker resources](https://distributed.readthedocs.io/en/latest/resources.html#worker-resources) with `dask-ml`? 

Or would I need to manually do it on my own by combining `dask-delayed` and doing manual resource management from the link above? 

---

If my hypothesis is wrong, do you know what the issue might be? Happy to provide logs or errors but I'm not sure what is or isn't relevant

Thank you so much for your time!

**Comment by TomAugspurger** [comment]
Do you have an example showing this? Might help make things more concrete. In particular it'd be nice to know if you're using `dask_ml.model_selection.GridSearchVV` or the version from scikit-learn with the distributed joblib backend.

**Comment by IanQS** [comment]
Sorry for the late response! Please know I'm still working on a reproducible example but I'm using  the dask-ml version

**Comment by TomAugspurger** [comment]
Thanks. Two more questions: how many cores per worker do you have, and are you using any parallelism at the scikit-learn level (with `n_jobs`)?

**Comment by IanQS** [comment]
Tom,

I'm attaching it below. The example here uses `LightGBM` but I noticed that it wasn't saturating the workers even when using `dask-ml` models and `sklearn` models

2 cores, 4 cpus and 7Gigs of memory

It's an `.ipynb` file but github doesn't let me attach `.ipynb` so I had to convert it to a text first. Thanks for your help! LMK if I can support you in any way on this

[reproducible_error_for_issue.txt](https://github.com/dask/dask-ml/files/4278021/reproducible_error_for_issue.txt)

**Comment by TomAugspurger** [comment]
Thanks. If you're able to simplify things down to a minimal example I'll be able to help more quickly. See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. Ideally, it'd be a simple script that you can just include in your original post.

**Comment by IanQS** [comment]
Hey Tom! 

```
import sys
from types import ModuleType, FunctionType
from gc import get_referents

BLACKLIST = type, ModuleType, FunctionType

from dask.distributed import Client, LocalCluster
from sklearn.datasets import make_circles
from sklearn.linear_model import LogisticRegression as skLogReg
from dask_ml.model_selection import GridSearchCV
import numpy as np
import time

np.random.seed(1234)

N_WORKERS=4
DATASET_SIZE = 10_000_000  # 200 Mil -> 4.8 GB, 1M -> 55MB
BASE_WORKER_MEMORY_CONSUMPTION = 121

def getsize(obj):
    """sum size of object & members."""
    if isinstance(obj, BLACKLIST):
        raise TypeError('getsize() does not take argument of type: '+ str(type(obj)))
    seen_ids = set()
    size = 0
    objects = [obj]
    while objects:
        need_referents = []
        for obj in objects:
            if not isinstance(obj, BLACKLIST) and id(obj) not in seen_ids:
                seen_ids.add(id(obj))
                size += sys.getsizeof(obj)
                need_referents.append(obj)
        objects = get_referents(*need_referents)
    return size

def get_curr_worker_count(client):
    return len(client.get_worker_logs())

params = {
    "C": [20 for _ in range(2)],
    "max_iter": [20 for _ in range(2)],
}


if __name__ == "__main__":
    local_cluster = LocalCluster()

    client = Client(local_cluster)
    time.sleep(5)

    X, y = make_circles(n_samples=DATASET_SIZE)

    size_X_mb = getsize(X) * 1e-6
    size_y_mb = getsize(y) * 1e-6
    dataset_size = size_X_mb + size_y_mb
    print(f"Size of X: {size_X_mb} MB")
    print(f"Size of y: {size_y_mb} MB")
    print(f"Dataset size: {dataset_size} MB")
    print(f"Total memory on single: {size_X_mb + size_y_mb + BASE_WORKER_MEMORY_CONSUMPTION} Mb")
    print(f"Total memory on altogethewr: {(size_X_mb + size_y_mb + BASE_WORKER_MEMORY_CONSUMPTION) *4} Mb")

    model = skLogReg()

    grid_search_cv = GridSearchCV(
        estimator=model, 
        param_grid=params, 
        scheduler=client,
        return_train_score='True',
        n_jobs=-1
    )

    client.restart()

    grid_search_cv.fit(X, y)
```

A few things to note:

1) 1 worker seems to be doing a majority of the work

2) 1 other worker gets SOME data but doesn't seem to be doing anything?

3) the consumption of memory on the single worker doing all the work seems to be larger than all the data (1.4Gb across 4 workers)

4) the worker seems to get killed around 2GB of memory usage when the limit is 4GB

**Comment by TomAugspurger** [comment]
Things seem for me locally. What's happening on the dashboard for you? You might include the output of a performance report: https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports

**Comment by IanQS** [comment]
Do you get the case where 1 or 2 worker(s) seem to get all the work while all the others are sitting around (in terms of CPU and memory consumption)?

The file itself is VERY large (the rendered Chrome visualization is less messy) and Github doesn't support uploading HTML. I'm uploading it as a text file if that works 
[dask-report.html.txt](https://github.com/dask/dask-ml/files/4301228/dask-report.html.txt)
