### ISSUE TITLE
OneHotEncoder inverse_transform with datetime64[ns] does not preserve other column dtypes

### ISSUE THREAD

**Issue by jocelynjyl** [dask/dask-ml#624]
I'm not sure if this is an issue with dask, dask-ml or something else altogether. I've noticed after calling inverse_transform where the dataframe contains a column of datetime64[ns], the non-categorical columns all become 'object' type. 

As a side effect, you can't directly do df.to_parquet('output') on the inverse_transform dataframe. df.compute().to_parquet('output') works sometimes.  

Version info: 
>>> dask.__version__
'2.10.1'
>>> dask_ml.__version__
'1.2.0'

Errors I've seen so far: 
```
ValueError: Error converting column "id" to bytes using encoding UTF8. Original error: bad argument type for built-in operation
```
```
ValueError: Don't know how to convert data type: datetime64[ns, UTC]
```

Minimal code example: 
Following an example found here: [https://github.com/dask/dask-ml/issues/362#issuecomment-420283078]

```
import dask.dataframe as dd
from dask_ml.preprocessing import DummyEncoder, Categorizer

df = dd.demo.make_timeseries()
df.x = dd.to_datetime(df.x)
cat = Categorizer(columns=['name'])
de = DummyEncoder()
df_cat = cat.fit_transform(df)
encoded = de.fit_transform(df_cat)
decoded = de.inverse_transform(encoded.values)

>>> df
Dask DataFrame Structure:
                   id    name               x        y
npartitions=11                                        
2000-01-31      int64  object  datetime64[ns]  float64
2000-02-29        ...     ...             ...      ...
...               ...     ...             ...      ...
2000-11-30        ...     ...             ...      ...
2000-12-31        ...     ...             ...      ...
Dask Name: assign, 44 tasks
>>> decoded
Dask DataFrame Structure:
                    id             name       x       y
npartitions=11                                         
0               object  category[known]  object  object
250560             ...              ...     ...     ...
...                ...              ...     ...     ...
2626560            ...              ...     ...     ...
2894399            ...              ...     ...     ...
Dask Name: getitem, 275 tasks
```

**Comment by TomAugspurger** [comment]
Thanks for the example.

I'm not sure I'd expect the inverse_transform to operate when you have an array (which you are with the `.values`). That's going to be upcast to object dtype, so all the type information is lost.

**Comment by TomAugspurger** [comment]
A bit simpler example. Perhaps there is something that could be done, not sure

```python

In [17]: df = dd.from_pandas(pd.DataFrame({"A": pd.to_datetime(['2000', '2001']), "B": pd.Categorical(['a', 'b'])}), 2)

In [18]: de = DummyEncoder()

In [23]: result = de.inverse_transform(de.fit_transform(df).to_dask_array(lengths=True))

In [24]: result.dtypes
Out[24]:
A      object
B    category
dtype: object

In [25]: result.compute()
Out[25]:
           A  B
0 2000-01-01  a
1 2001-01-01  b
```

Regardless, I'd recommend avoiding the conversion to object dtype.

**Comment by jocelynjyl** [comment]
Thanks for the quick feedback and explanation.

This is a bit of a rabbit hole for me since I ran into the same issue as in #362 (though the error message is worded slightly differently now.) So I tried the suggested workaround passing .values and then couldn't get it to output to parquet nicely. 

For now I'll just recast the columns back to the dtypes I expect. Sorry for the noise! 

P.S. any idea when #362 might be resolved?

**Comment by TomAugspurger** [comment]
I'm not sure about #362. If you're interested in working on it, we'd be grateful.

**Comment by TomAugspurger** [comment]
What's left in this issue?

We have https://github.com/dask/dask-ml/issues/362 about DummyEncoder handing non-numeric divisions.

I don't think we should encourage mixing datetimes and numeric dtypes into an object-dtype (which is what `.values` does).  Rather, a ColumnTransformer should be used.

**Comment by jocelynjyl** [comment]
Thanks. I'll take a look at 362 and see if there's something I can do there.
