### ISSUE TITLE
dask_ml.model_selection.GridSearchCV throwing error "assert not is_dask_collection(x)" even when inputs are dask dataframes

### ISSUE THREAD

**Issue by SonyFrancis** [dask/dask-ml#647]
I am getting this issue even when my inputs to the dask_ml.model_selection.GridSearchCV function is a dask dataframe

Code below:
import dask
import joblib
import numpy as np
import pandas as pd
import dask.dataframe as dd
from dask_ml.preprocessing import StandardScaler
from dask_ml.preprocessing import Categorizer, OrdinalEncoder
from dask.distributed import Client

data = pd.DataFrame({"x0":[1,1,2,2,2,2,2,1,1], "x1":[1,1,3,5,5,5,5,1,1],
"x2": [1.5,2.6,0,0,0,0,0,1.3,3.7], "x3":[1,1,1,1,2,1,2,1,1], "x4" :["N","N","N","N","N","N","N","Y","N"],
"x5" :[151,239,236,193,193,193,193,163,229], "x6":[239,246,236,193,193,193,193,229,7],
"x7":[1,1,1,2,2,2,2,1,1], "x8":[7,14,4.5,3.5,52,3.5,52,6.5,13.5],
"x9":[0.5,0.5,0.5,0.5,0,0.5,0,0.5,0.5], "x10":[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5],
"x11":[1.65,1,0,0,0,0,0,1.25,3.7], "x12":[0,0,0,0,0,5.76,0,0,0],
"x13":[0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3], "target":[9.95,16.3,5.8,7.55,55.55,13.31,55.55,9.05,18.5]})
data = dd.from_pandas(data,npartitions=1)

label_vars = ['x0', 'x1', 'x3', 'x4', 'x7', 'x9', 'x10', 'x13']
numeric_vars = ['x2', 'x5', 'x6', 'x8', 'x11', 'x12']
cat = Categorizer(columns=label_vars)
data= cat.fit_transform(data)

en = OrdinalEncoder(columns=label_vars)
data = en.fit_transform(data)

sc = StandardScaler()
data[numeric_vars] = sc.fit_transform(data[numeric_vars])

X=data.drop(["target"], axis = 1)
y=data["target"]
client = Client(processes=False)
with joblib.parallel_backend('dask'):
     model1 = RandomForestRegressor()
     params = {'max_depth': [3,4,5], 'n_estimators':[100,200,300,400,500], 'min_samples_split':
                    [2,3,4,5,6], 'min_samples_leaf': [1, 3]}
     model = GridSearchCV(model1,params)
     model.fit(X,y)

#----------------------Error----------------------------#
X-type:<class 'dask.dataframe.core.DataFrame'>, Y-type:<class 'dask.dataframe.core.Series'>
Traceback (most recent call last):
File ".\testing_dask_inprogress.py", line 290, in
model.fit(X,y)
File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\model_selection_search.py", line 1233, in fit
cache_cv=self.cache_cv,
File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\model_selection_search.py", line 203, in build_cv_graph
X_name, y_name, groups_name = to_keys(dsk, X, y, groups)
File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\model_selection\utils.py", line 87, in to_keys
assert not is_dask_collection(x)
AssertionError

**Comment by TomAugspurger** [comment]
What version of dask-ml?

**Comment by SonyFrancis** [comment]
Versions:
dask - 2.12.0                    
dask-core - 2.12.0
dask-glm - 0.2.0 
dask-ml - 1.2.0  
dask-xgboost - 0.1.10

**Comment by TomAugspurger** [comment]
Can you try with dask-ml 1.3.0 or master?

**Comment by SonyFrancis** [comment]
Thanks @TomAugspurger . Its working now. Is this version of dask-ml stable one, just asking because when I simply do pip install dask-ml, it installs the 1.2.0 version

**Comment by TomAugspurger** [comment]
The latest version on PyPI is 1.3.0: https://pypi.org/project/dask-ml/
