### ISSUE TITLE
GridSearchCV fails with XGBoost models

### ISSUE THREAD

**Issue by moneygeek** [dask/dask-ml#667]
The following code fails:

```
import numpy as np
from dask_ml.model_selection import GridSearchCV, KFold
from dask_xgboost import XGBClassifier

x = np.random.randn(100, 2)
y = np.random.randint(0, 1, 100)

params = {'max_depth': [2, 3]}

clf = GridSearchCV(XGBClassifier(), params, cv=KFold(n_splits=2), scoring='neg_mean_squared_error')
clf.fit(x, y)
```

Stack trace:
```
  File "/home/jin/anaconda3/envs/ml-gpu/lib/python3.6/site-packages/dask_ml/model_selection/_normalize.py", line 38, in normalize_estimator
    val = getattr(est, attr)
  File "/home/jin/anaconda3/envs/ml-gpu/lib/python3.6/site-packages/xgboost/sklearn.py", line 536, in feature_importances_
    b = self.get_booster()
  File "/home/jin/anaconda3/envs/ml-gpu/lib/python3.6/site-packages/xgboost/sklearn.py", line 200, in get_booster
    raise XGBoostError('need to call fit or load_model beforehand')
xgboost.core.XGBoostError: need to call fit or load_model beforehand
```

The error arises because the `normalize_estimator` function is trying to get the 'feature_importances_' attribute of the xgb model, but the attribute doesn't exist unless the model has already been trained. The `normalize_estimator` function I believe should gloss over this error, but it doesn't because it's not catching the `XGBoostError` error type.

**Comment by TomAugspurger** [comment]
I think this is an issue with XGboost. I think that the error they raise there should be subclassing `AttributeError` to make it clear that you're accessing a non-existent attribute.

Can you propose that change on xgboost and link to the discussion here? If they decline that change we could perhaps include XGBoostError in the exceptions we catch, but I would need to think about that more.

**Comment by blinickg** [comment]
Proposed the change.

**Comment by trivialfis** [comment]
Toke some time on passing the estimator checks from skl, it should actually be `NotFittedError`.

**Comment by trivialfis** [comment]
How do you use dask ml with numpy?

```
/home/fis/Workspace/XGBoost/scikit-learn/sklearn/utils/validation.py:72: FutureWarning: Pass classifier=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)
Traceback (most recent call last):
  File "reproduce.py", line 11, in <module>
    clf.fit(x, y)
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/dask_ml/model_selection/_search.py", line 1271, in fit
    out = scheduler(dsk, keys, num_workers=n_jobs)
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/dask_ml/model_selection/methods.py", line 158, in cv_split
    return CVCache(list(cv.split(X, y, groups)), is_pairwise, cache, _num_samples(X))
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/dask_ml/model_selection/_split.py", line 247, in split
    chunks = X.chunks[0]
AttributeError: 'numpy.ndarray' object has no attribute 'chunks'
```

**Comment by TomAugspurger** [comment]
The first example at
https://ml.dask.org/modules/generated/dask_ml.model_selection.GridSearchCV.html#dask_ml.model_selection.GridSearchCV
has an example.

```python

>>> import dask_ml.model_selection as dcv>>> from sklearn import svm, datasets>>> iris = datasets.load_iris()>>> parameters = {'kernel': ['linear', 'rbf'], 'C': [1, 10]}>>> svc = svm.SVC()>>> clf = dcv.GridSearchCV(svc, parameters)>>> clf.fit(iris.data, iris.target)  # doctest: +NORMALIZE_WHITESPACE +ELLIPSIS
```

Do you have an example of this not working?

**Comment by trivialfis** [comment]
Got it.  The script provided in the issue should be modified into using single node XGB instead of dask Xgboost.

**Comment by blinickg** [comment]
@trivialfis , do you mean calling `import xgboost as xgb` and then using `clf = GridSearchCV(xgb.XGBClassifier(), params, cv=KFold(n_splits=2), scoring='neg_mean_squared_error')`
instead of `clf = GridSearchCV(dask_xgboost.XGBClassifier(), params, cv=KFold(n_splits=2), scoring='neg_mean_squared_error')`

**Comment by blinickg** [comment]
@trivialfis , do you mean @moneygeek 's script? I get the error you get `AttributeError: 'numpy.ndarray' object has no attribute 'chunks'` when I use xgboost.XGBClassifier().

**Comment by trivialfis** [comment]
Let me take a deeper look later.

**Comment by trivialfis** [comment]
Just tried the example provided by @TomAugspurger .  You will get `AttributeError: 'numpy.ndarray' object has no attribute 'chunks'` if you use the parameter `cv`.

**Comment by TomAugspurger** [comment]
dask_ml.model_selection.KFold doesn't accept ndarrays, just dask arrays.

**Comment by blinickg** [comment]
Ah, I missed that. Thanks @TomAugspurger and @trivialfis .

To recap then, the original code needs to be modified in 3 ways:
1) upgrade xgboost library to 1.1.0. 
2) use the xgboost library for the classifier instead of dask_xgboost.
3) use sklearn.model_selection.KFold instead of dask_ml.model_selection.KFold

So dask only enters this code then as the GridSearchCV.

**Comment by TomAugspurger** [comment]
Yep, that sounds right to me. Thanks @blinickg and @trivialfis.

**Comment by blinickg** [comment]
@TomAugspurger, I think you closed the issue too soon.

We want to use dask's XGBClassifier to avoid loading all data into memory at once. the only reason for using dask's GridSearchCV is so we can use dask's XGBClassifier.
so using xgb.XBGClassifier defeats the purpose.

When I change the script to use dask_xgboost.XGBClassifier() instead of xgboost.XGBClassifier(), I get the error ```ValueError: No clients found
Start a client and point it to the scheduler address
  from distributed import Client
  client = Client('ip-addr-of-scheduler:8786')```

I googled and found [this](https://github.com/dask/dask-xgboost/issues/21) thread from you containing the same error, but it doesn't look like it was resolved.

**Comment by TomAugspurger** [comment]
XGBoost has a native dask integration that (AFAIK) avoids loading all the data onto a single node. Do you still need dask-xgboost's XGBClassifier?

**Comment by blinickg** [comment]
Sounds good.

For clarity's sake, this is what the original script looks like now:
```
import numpy as np
import dask_ml.model_selection as dcv
import dask_xgboost
import sklearn.model_selection

x = np.random.randn(100, 2)
y = np.random.randint(0, 1, 100)

params = {'max_depth': [2, 3]}

clf = dcv.GridSearchCV(dask_xgboost.XGBClassifier(), params, cv=sklearn.model_selection.KFold(n_splits=2), scoring='neg_mean_squared_error')
clf.fit(x, y)
```
I have also run `dask-scheduler` from my command line prior to running the script and the output in terminal is that the scheduler is at 8786 and the dashboard is at 8787.

**Comment by TomAugspurger** [comment]
I think you would also need a `client = Client('ip-of-scheduler')` in that script. Or more simply, just `client = Client()` without starting anything else from the commandline.

**Comment by blinickg** [comment]
do you mean this?
```
import numpy as np
import dask_ml.model_selection as dcv
import dask_xgboost
import sklearn.model_selection
from distributed import Client

client = Client(processes=False)

x = np.random.randn(100, 2)
y = np.random.randint(0, 1, 100)

params = {'max_depth': [2, 3]}

clf = dcv.GridSearchCV(dask_xgboost.XGBClassifier(), params, cv=sklearn.model_selection.KFold(n_splits=2),
                       scoring='neg_mean_squared_error', scheduler=client)
clf.fit(x, y)
```

**Comment by blinickg** [comment]
@TomAugspurger if I understand the issue in dask/dask-xgboost#21 correctly, it's that the issue is with dcv.GridSearchCV and dcv.RandomizedSearchCV don't work properly with XGBoost in Dask-ML. Can you confirm?

Also, can you let me know if the code directly above should be modified in any way?

Thanks for all your hard work.

**Comment by trivialfis** [comment]
Hi @blinickg  is there any problem for using native xgboost classifier?

**Comment by blinickg** [comment]
Hi @trivialfis,

The reason we'd want to use dask's XGBClassifier is to avoid loading all data into memory at once. 

Dask XGBoost seems to have a memory leakage issue though.

**Comment by TomAugspurger** [comment]
`dask_xgboost.XGBoostClassifier` doesn't implement out-of-core training. It
loads the data into *distributed* memory, and hands that off to xgboost's
distributed runtime.

My understanding is that the native `xgboost.dask.XGBoostClassifier` does
the same thing.

**Comment by rrpelgrim** [comment]
I'm running into the same issue today. Do I understand correctly that there's no way to implement `dask_xgboost.XGBoostClassifier` with `dask_ml.model_selection.GridSearchCV` ?
