### ISSUE TITLE
Transfer large synthetic data approach from dask-glm

### ISSUE THREAD

**Issue by PeterDSteinberg** [dask/dask-ml#67]
See [make_poisson and similar functions in dask-glm's datasets.py](https://github.com/dask/dask-glm/blob/master/dask_glm/datasets.py).  Transfer that approach into `dask-ml`'s `datasets.py` so larger synthetic data sets can be created.  Currently the approach in `dask-ml`'s `datasets.py` just wraps `sklearn.datasets`.

**Comment by mrocklin** [comment]
I also ran into this just last night
