### ISSUE TITLE
PCA with dataframe can't  real explained_variance_ratio_ except nan

### ISSUE THREAD

**Issue by sosofun** [dask/dask-ml#681]
**What happened**:

when use dask_ml.decomposition.PCA fit the dask.dataframe， then will get the nan of pca Attributes  pca.explained_variance_ratio_/explained_variance_  ; maybe can't get  the dataframe shape lead to the error.

**What you expected to happen**:
[0.99244289 0.00755711]

**Minimal Complete Verifiable Example**:
[nan nan]

```python
# Put your MCVE code here
import dask.dataframe as dd
import dask.array as da
import numpy as np
from dask_ml.decomposition import PCA

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
dX = da.from_array(X, chunks=X.shape)
pca = PCA(n_components=2)
pca.fit(dX)
print(pca.explained_variance_ratio_)
#the result is [0.99244289 0.00755711]


df = dd.from_dask_array(dX, columns=['a','b'])
pca = PCA(n_components=2, svd_solver='full')
pca.fit(df)
print(pca.explained_variance_ratio_)
#the result is [nan nan]
```

**Anything else we need to know?**:

**Environment**:
python 3.6
dask                      2.18.1
dask-glm                  0.2.0
dask-ml                   1.5.0
dask-xgboost              0.1.10

- Dask version:
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by sosofun** [comment]
have fix it  with :https://github.com/dask/dask-ml/pull/682/commits/ff66a196b862d569c6895db44b21dbdcf71ace5f

**Comment by zexuan-zhou** [comment]
I encountered the similar issue. Looking forward to the solution to be merged

**Comment by TomAugspurger** [comment]
The PR at https://github.com/dask/dask-ml/pull/682 has stalled. Perhaps we give @sosofun a few days to respond, and if they haven't then you make a new PR @zexuan-zhou?

**Comment by zexuan-zhou** [comment]
> The PR at #682 has stalled. Perhaps we give @sosofun a few days to respond, and if they haven't then you make a new PR @zexuan-zhou?

Sounds great. Thank you!

**Comment by TomAugspurger** [comment]
@zexuan-zhou I just closed #682, if you're interested in working on it.

**Comment by zexuan-zhou** [comment]
> @zexuan-zhou I just closed #682, if you're interested in working on it.

I tried converting my dask dataframe to a dask array to see if `explained_variance_ratio_` shows up (according to the example given in this issue it should). However it doesn't show up either. I think it's because the dask array I feed to `PCA` has unknown length (due to reading from multiple parquet files without gathering statistics). I wonder if you have any quick intuition what to do in this situation.

**Comment by TomAugspurger** [comment]
`DataFrame.to_dask_array(lengths=True)` will give you a Dask Array with known partition lengths, at the cost of computing them.

**Comment by zexuan-zhou** [comment]
@TomAugspurger I've started working on this. But based on my reading of the current code I don't see an easy way to get the actual shape of a dask dataframe without precomputing.
Specifically I'm referring to this line: 
https://github.com/sosofun/dask-ml/blob/4fe3af2d26d7d83a673befd40b32eab049258a75/dask_ml/decomposition/pca.py#L267
For a dask array, X.shape gives you the actual shape. However for a dask dataframe, `df_X.value.shape` gives you a delay.
Wonder if you have any good thoughts on it.

**Comment by TomAugspurger** [comment]
> I don't see an easy way to get the actual shape of a dask dataframe without precomputing.

That's correct. So we'll need to figure out the actual value of `n_samples` in the large compute at https://github.com/sosofun/dask-ml/blob/4fe3af2d26d7d83a673befd40b32eab049258a75/dask_ml/decomposition/pca.py#L329. Everything that depends on `n_samples` (like explained_variance_ratio) will also need to be figured out then.

**Comment by zexuan-zhou** [comment]
> > I don't see an easy way to get the actual shape of a dask dataframe without precomputing.
> 
> That's correct. So we'll need to figure out the actual value of `n_samples` in the large compute at https://github.com/sosofun/dask-ml/blob/4fe3af2d26d7d83a673befd40b32eab049258a75/dask_ml/decomposition/pca.py#L329. Everything that depends on `n_samples` (like explained_variance_ratio) will also need to be figured out then.

@TomAugspurger I have two solutions in mind:

1. Use `dask.dataframe.Dataframe.to_dask_array(lengths=True)` when converting input dask.dataframe to dask.array here:https://github.com/sosofun/dask-ml/blob/4fe3af2d26d7d83a673befd40b32eab049258a75/dask_ml/decomposition/pca.py#L254. Since this is precomputing, we can raise a warning here telling the user what's happening, and suggest that it's best to feed the input as a dask.array to avoid this precomputing
2. Split the computation of `explained_variance = (S ** 2) / (n_samples - 1)`. That is, compute `S` and `n_samples` first, and then calculate `explained_variance` in memory since usually `S` is of small size, and `n_samples` is just a constant

**Comment by TomAugspurger** [comment]
Ideally everything is done in a single compute. I haven't checked if that's
possible though.

**Comment by eric-czech** [comment]
FYI this appears to work well with something like this:

```python
(
    (self.n_samples_, self.n_features_),
    self.components_,
    self.singular_values_
) = compute(
    dask.delayed(lambda x: x.shape)(X),
    components,
    singular_values
)
```

**Comment by eric-czech** [comment]
This is fixed now btw.

```python
import dask.dataframe as dd
import dask.array as da
import numpy as np
from dask_ml.decomposition import PCA

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
dX = da.from_array(X, chunks=X.shape)
pca = PCA(n_components=2)
pca.fit(dX)
print(pca.explained_variance_ratio_)
[0.99244289 0.00755711]

df = dd.from_dask_array(dX, columns=['a','b'])
pca = PCA(n_components=2, svd_solver='full')
pca.fit(df)
print(pca.explained_variance_ratio_)
[0.99244289 0.00755711]
```

**Comment by TomAugspurger** [comment]
Thanks for following up.
