### ISSUE TITLE
feature request: mean absolute percentage error

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-ml#691]
Add mean absolute percentage error here
https://github.com/dask/dask-ml/blob/master/dask_ml/metrics/regression.py

using https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/metrics/_regression.py#L197

**Comment by TomAugspurger** [comment]
Agreed, that would be welcome. https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html (generally, anything in `sklearn.metrics` should be considered in-scope.
