### ISSUE TITLE
HyperbandSearchCV not allow 3D input

### ISSUE THREAD

**Issue by sim-san** [dask/dask-ml#721]
Hi,

in this line the algorithm checks the input data:
https://github.com/dask/dask-ml/blob/6eac8a0e48d09ee2670802cf9f48de63e2593460/dask_ml/model_selection/_split.py#L151
And does not allow input data with more than two dimensions.

my suggestion is to add the following parameters to `check_array()`:
- `ensure_2d=False`
- `allow_nd=True`

**Comment by stsievert** [comment]
What motivated this issue and the associated PR? I'm guessing this is important for PyTorch image datasets, which are of shape `(batch_size, n_color, width, height)`.

**Comment by sim-san** [comment]
I am using it with scikeras and 3-dimensional input `(batch_size, timesteps, features)` for LSTM Networks
