### ISSUE TITLE
Please add BOHB (Bayesian Optimization and Hyperband) to daskml for hyperparameters searching

### ISSUE THREAD

**Issue by UTUnex** [dask/dask-ml#730]
The existed hyperbandsearchCV() is a combination of early stopping and random search. Could you please consider adding the bohbsearchCV() which is a combination of early stopping and bayes optimization search?
Thank you.

**Comment by stsievert** [comment]
We are considering a BOHB implementation. See #697 for more detail.

What prompted this issue? What would you use a BOHB implementation for?

**Comment by TomAugspurger** [comment]
Let's have that discussion over in #697.
