### ISSUE TITLE
PCA for short-fat arrays

### ISSUE THREAD

**Issue by eric-czech** [dask/dask-ml#731]
Assuming I wanted to run non-randomized PCA on a short and fat array (chunks only along columns), is there a way to do that using the current dask-ml PCA implementation?

**Comment by TomAugspurger** [comment]
The memory usage is outlined in the notes at https://docs.dask.org/en/latest/array-api.html#dask.array.linalg.tsqr. So it should finish as long as the chunks are too big, it might just be slow?

**Comment by eric-czech** [comment]
Thanks @TomAugspurger, but this is what I mean (i.e. PCA.fit won't define the arrays):

```python
from dask_ml.decomposition import PCA
# Chunk along columns but not rows
x = da.random.random(size=(100, 1000)).rechunk((-1, 50))
PCA(svd_solver='full').fit(x) # full or auto calls da.linalg.svd
...
/opt/conda/lib/python3.7/site-packages/dask_ml/decomposition/pca.py in _fit(self, X)
    272 
    273         if solver in {"full", "tsqr"}:
--> 274             U, S, V = da.linalg.svd(X)
    275         else:
    276             # randomized
...
ValueError: Input must have the following properties:
  1. Have two dimensions
  2. Have only one column of blocks

Note: This function (tsqr) supports QR decomposition in the case of
tall-and-skinny matrices (single column chunk/block; see qr)Current shape: (100, 1000),
Current chunksize: (100, 50)
```

I could call `da.linalg.svd` myself with the transposed matrix input and use whatever formulas there are that equate the singular vectors for a transposed input (iirc it's possible), but the current PCA code wouldn't work as is.  I wanted to see if this has come up before though I don't see any related issues.  It's a fairly common use case in genetics (cc: @mrocklin).

**Comment by mrocklin** [comment]
> I could call da.linalg.svd myself with the transposed matrix input and use whatever formulas there are that equate the singular vectors for a transposed input (iirc it's possible), but the current PCA code wouldn't work as is

This would be my first instinct.  (indeed, we might put this logic into `da.linalg.svd` directly?) 

Are there problems that you ran into, or that you think you would run into with this approach?

**Comment by eric-czech** [comment]
> Are there problems that you ran into, or that you think you would run into with this approach?

No not really except that some PCA implementation is available in the general domain for in memory arrays, tall-skinny ones, or fully chunked ones, but short-fat ones are just common enough (as will be the desire to avoid non-deterministic results) that I'd like to find a good solution for them.  It will be awkward to write something into sgkit for just that without supporting all of them and I'd like to see us avoid it if we can.

In principle, I guess it's as simple as this:

```python
import dask.array as da
import numpy as np 

x = da.random.random(size=(1000, 100)).rechunk((-1, -1))

# Run on tall-skinny array
u, s, v = da.linalg.svd(x)
pcs1 = v.compute()

# Run on transposition to short-fat array (USV becomes VtSUt)
vt, s, ut = da.linalg.svd(x.T)
pcs2 = vt.T.compute()

# Make sure the PCs are the same (modulo signs)
all([
    np.allclose(pcs1[i], pcs2[i]) or 
    np.allclose(pcs1[i], -pcs2[i]) 
    for i in range(x.shape[1])
])
> True
```

There are several other references to shapes and axes in the current PCA implementation that would keep this from working as-is, even if it is that simple to get the original components using a transposed input.  

If there was a way for it to be handled transparently in `da.linalg.svd`, that would be terrific.  It wasn't clear to me in a glance at that code why `compute_svd` is an option on `tsqr` but not `sfqr`.  Maybe it would be trivial otherwise?

**Comment by mrocklin** [comment]
I have a hazy memory of trying this logic, but finding that singular
values/vectors switched sign when I transposed, and so bailed on the effort
due to not wanting to think about it.

I could be fabricating that memory though.  In any event, I'm +1 if anyone
wants to pick this up.  My guess is that it would be a small code
contribution with some nice effects.

**Comment by eric-czech** [comment]
>  In any event, I'm +1 if anyone wants to pick this up

Which of these makes the most sense to pick up @mrocklin?

1. Have `linalg.svd` identify short-fat arrays, transpose them, run the normal tsqr code, and then transpose results (assuming there are no other pitfalls with that)
2. Have some equivalent to `tsqr` that can operate on short-fat arrays.  `sfqr` sounds like this but on closer inspection it looks like a neglected counterpart to tsqr that has fallen well behind.  The docstring still calls it a "quick hack" in any case.

The second option sounds better, but are there many contributors that know the tsqr code well still and could advise on a sfqr implementation / revamp?  

I would happily take on \#1, and possibly \#2 if I could get some substantial help from the start.

**Comment by TomAugspurger** [comment]
If option 1 works then it sounds like less work. I'm not sure that we have
anyone who is really an expert on the tsqr code.

**Comment by mrocklin** [comment]
+1 on option 1.  I think that tsqr should satisfy our needs.  And if we can
have only one really complicated function rather than two then that would
be my preference for maintenance reasons.

**Comment by eric-czech** [comment]
Feel free to close this, otherwise I'll leave it open until I get a chance to explore those changes some more.

**Comment by TomAugspurger** [comment]
I'm happy to leave this open till we have a resolution.

**Comment by jerowe** [comment]
@eric-czech  I was just coming here to raise this issue!

I have a PR with some different shaped arrays to demonstrate that dask-ml PCA fails on skinny arrays, which would be mostly all of our arrays. ;-) 

https://github.com/pystatgen/sgkit/blob/6dcf446583bc52de5e15bae65f4aa63fcc5bb9b7/sgkit/tests/test_decomposition.py#L239

**Comment by eric-czech** [comment]
Hey @TomAugspurger quick question -- we have some minor time pressure to do some useful things with PCA in our project and I was curious what happens once some of these other dask changes go through (probably https://github.com/dask/dask/issues/6620 next).  Once those go in to a dask release, what's the release cycle for dask-ml like?  Is it a very drastic change if the fix for this issue requires a version constraint on dask at the newest release or higher?

**Comment by TomAugspurger** [comment]
Releasing dask-ml is not a problem at all and I'm happy to do one as soon as you're ready.

As for what to do code-wise, my slight preference is to have a bit of compatibility code in dask-ml that makes use of the new SVD things only if the version of Dask installed is new enough (2.26.0 say). How does that sound to you?

**Comment by eric-czech** [comment]
> my slight preference is to have a bit of compatibility code in dask-ml that makes use of the new SVD things only if the version of Dask installed is new enough (2.26.0 say).

Yea sounds great, so basically I'd create a constant in https://github.com/dask/dask-ml/blob/master/dask_ml/_compat.py and check against it?

**Comment by TomAugspurger** [comment]
Yep that sounds right.

**Comment by eric-czech** [comment]
I'll close this out since most of the necessary Dask changes were in https://github.com/dask/dask/pull/6591 and the last of the related changes here in https://github.com/dask/dask-ml/pull/742.

For posterity, this will work now with dask >= 2.28.0 and dask-ml >= 1.7.0.
