### ISSUE TITLE
ContextualVersionConflict error when:  import dask_ml

### ISSUE THREAD

**Issue by gitclem** [dask/dask-ml#733]
**What happened**:
I'm trying to install dask-ml and import it.  Unfortunately, I get the error ContextualVersionConflict (which doesn't 't mean anything to me and google doesn't seem to have a good explanation of this.  Google shows a lot of examples where this occurs.)

**What you expected to happen**:
no complaints upon importing.

**Minimal Complete Verifiable Example**:

```python
# In JupyterLab
!pip install "dask[complete]"   --upgrade
!pip install "dask-ml[complete]"   --upgrade
import dask_ml

---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-3-aaa999715058> in <module>
----> 1 import dask_ml

/usr/local/lib/python3.7/dist-packages/dask_ml/__init__.py in <module>
      7 
      8 try:
----> 9     __version__ = get_distribution(__name__).version
     10     __all__.append("__version__")
     11 except DistributionNotFound:

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in get_distribution(dist)
    470         dist = Requirement.parse(dist)
    471     if isinstance(dist, Requirement):
--> 472         dist = get_provider(dist)
    473     if not isinstance(dist, Distribution):
    474         raise TypeError("Expected string, Requirement, or Distribution", dist)

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in get_provider(moduleOrReq)
    342     """Return an IResourceProvider for the named module or requirement"""
    343     if isinstance(moduleOrReq, Requirement):
--> 344         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    345     try:
    346         module = sys.modules[moduleOrReq]

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in require(self, *requirements)
    890         included, even if they were already activated in this working set.
    891         """
--> 892         needed = self.resolve(parse_requirements(requirements))
    893 
    894         for dist in needed:

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    781                 # Oops, the "best" so far conflicts with a dependency
    782                 dependent_req = required_by[req]
--> 783                 raise VersionConflict(dist, req).with_context(dependent_req)
    784 
    785             # push the new requirements onto the stack

ContextualVersionConflict: (scikit-learn 0.20.3 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('scikit-learn>=0.23'), {'dask-ml'})
```

**Anything else we need to know?**:

**Environment**:
- Dask version:   2.25.0
- dask-ml 1.6.0
- Sklearn version 0.23.2
- Python version:  3.75
- Operating System:  Linux (AWS): 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
- Install method:  installed with pip inside Jupyter Lab

pip list

Package                                          Version
------------------------------------------------ ---------------
aar-grpc                                         0.0.3
aar-marketer                                     4.18
absl-py                                          0.5.0
adal                                             1.1.0
adconfig-data-service-domain-attribution-objects 1.12.6
adconfig-data-service-domain-attribution-queries 1.12.6
adconfig-data-service-domain-rtb-commands        1.12.6
adconfig-data-service-domain-rtb-objects         1.12.6
adconfig-data-service-domain-rtb-queries         1.12.6
adconfig-data-service-service-definitions-common 1.12.6
aerospike                                        3.7.0
aiohttp                                          3.6.2
alembic                                          1.0.0
altair                                           2.2.2
ansiwrap                                         0.8.3
appdirs                                          1.4.3
asn1crypto                                       0.24.0
astor                                            0.7.1
astunparse                                       1.6.3
async-generator                                  1.10
async-timeout                                    3.0.1
atomicwrites                                     1.4.0
attrs                                            18.2.0
Automat                                          0.7.0
awscli                                           1.16.185
azure-common                                     1.1.23
azure-core                                       1.8.0
azure-datalake-store                             0.0.31
azure-nspkg                                      2.0.0
azure-storage-blob                               2.1.0
azure-storage-common                             2.1.0
backcall                                         0.1.0
beautifulsoup4                                   4.9.1
behave                                           1.2.6
behave-pandas                                    0.3.0
bitarray                                         1.5.3
black                                            19.10b0
bleach                                           2.1.4
blis                                             0.4.1
bokeh                                            2.2.1
boto                                             2.49.0
boto3                                            1.9.175
botocore                                         1.12.175
bqplot                                           0.11.1
branca                                           0.3.1
brandprotobuf                                    3.6.2
Brotli                                           1.0.7
CacheControl                                     0.12.6
cachetools                                       2.1.0
cachy                                            0.3.0
certifi                                          2018.8.24
cffi                                             1.11.5
chardet                                          3.0.4
chart-studio                                     1.0.0
cleo                                             0.7.6
Click                                            7.0
clikit                                           0.4.3
cloudpickle                                      0.5.6
colorama                                         0.4.3
colorlover                                       0.3.0
colour                                           0.1.5
constantly                                       15.1.0
convertdate                                      2.2.1
cron-descriptor                                  1.2.21
cryptography                                     2.3.1
cryptography-vectors                             2.3.1
cufflinks                                        0.17.3
cvxpy                                            1.0.9
cycler                                           0.10.0
cymem                                            2.0.3
Cython                                           0.29.21
daff                                             1.3.40
dash                                             1.10.0
dash-bootstrap-components                        0.7.2
dash-core-components                             1.9.0
dash-html-components                             1.0.3
dash-qc-components                               0.0.1
dash-renderer                                    1.3.0
dash-table                                       4.6.2
dask                                             2.25.0
dask-glm                                         0.2.0
dask-kubernetes                                  0.10.0
dask-ml                                          1.6.0
dask-xgboost                                     0.1.11
dataclasses                                      0.6
datadog                                          0.27.0
dataplayground                                   1.0.145
dateparser                                       0.7.0
datrie                                           0.8
decorator                                        4.3.0
defusedxml                                       0.5.0
Deprecated                                       1.2.10
df2gspread                                       1.0.4
dill                                             0.3.2
distributed                                      2.24.0
dnspython                                        1.16.0
docopt                                           0.6.2
docutils                                         0.14
dx                                               0.2.4
ecos                                             2.0.7.post1
elasticsearch                                    6.3.1
entrypoints                                      0.3
escapism                                         1.0.0
experimentfr-analytics                           0.1.27
experimentfr-grpc                                0.1.27
fastcache                                        1.1.0
fbpca                                            1.0
fbprophet                                        0.5
findspark                                        1.3.0
flake8                                           3.8.3
Flask                                            1.0.3
Flask-Caching                                    1.9.0
Flask-Compress                                   1.5.0
fsspec                                           0.8.0
future                                           0.16.0
gast                                             0.2.0
gensim                                           3.8.0
geojson                                          2.5.0
gitdb                                            4.0.5
GitPython                                        3.1.7
Glances                                          3.1.5
google-api-python-client                         1.6.7
google-auth                                      1.5.1
google-auth-oauthlib                             0.4.1
google-pasta                                     0.2.0
googleapis-common-protos                         1.52.0
grpcio                                           1.20.0
grpcio-status                                    1.31.0
grpcio-tools                                     1.31.0
gspread                                          3.2.0
gunicorn                                         20.0.4
h5py                                             2.8.0
hdfs                                             2.1.0
HeapDict                                         1.0.1
holidays                                         0.9.12
html5lib                                         1.0.1
httplib2                                         0.18.1
hvac                                             0.9.1
hyperlink                                        18.0.0
idna                                             2.7
ijson                                            3.1.1
importlib-metadata                               1.7.0
incremental                                      17.5.0
invoke                                           1.4.1
ipaddress                                        1.0.22
ipydatawidgets                                   4.0.1
ipykernel                                        5.3.2
ipyleaflet                                       0.11.2
ipympl                                           0.3.3
ipyscales                                        0.2.2
ipython                                          7.12.0
ipython-genutils                                 0.2.0
ipyvolume                                        0.5.2
ipywebrtc                                        0.5.0
ipywidgets                                       7.5.1
isodate                                          0.6.0
itsdangerous                                     1.1.0
jedi                                             0.12.1
jeepney                                          0.4.3
Jinja2                                           2.10
jmespath                                         0.9.3
joblib                                           0.12.5
json5                                            0.9.5
jsonschema                                       3.2.0
jupyter                                          1.0.0
jupyter-client                                   6.1.3
jupyter-console                                  6.0.0
jupyter-contrib-core                             0.3.3
jupyter-contrib-nbextensions                     0.5.0
jupyter-core                                     4.6.3
jupyter-highlight-selected-word                  0.2.0
jupyter-kernel-gateway                           2.4.1
jupyter-latex-envs                               1.4.4
jupyter-nbextensions-configurator                0.4.0
jupyter-server-proxy                             1.5.0
jupyterhub                                       0.9.6
jupyterhub-kubespawner                           0.11.1
jupyterhub-ldapauthenticator                     1.2.2
jupyterlab                                       2.1.5
jupyterlab-code-formatter                        1.3.6
jupyterlab-dash                                  0.1.0a3
jupyterlab-git                                   0.20.0
jupyterlab-iframe                                0.2.1
jupyterlab-launcher                              0.13.1
jupyterlab-server                                1.2.0
jupytext                                         1.0.5
Keras                                            2.3.1
Keras-Applications                               1.0.8
Keras-Preprocessing                              1.1.2
keyring                                          20.0.1
kgrpc                                            1.0.9
kiwisolver                                       1.0.1
koalas                                           0.7.0
kubernetes                                       9.0.0
kubernetes-asyncio                               11.3.0
ldap3                                            2.5.1
llvmlite                                         0.32.1
locket                                           0.2.0
lockfile                                         0.12.2
lunardate                                        0.2.0
lxml                                             4.2.5
Mako                                             1.0.7
Markdown                                         3.0.1
MarkupSafe                                       1.1.1
matplotlib                                       3.0.0
mccabe                                           0.6.1
metadata-parser                                  0.9.23
mistune                                          0.8.3
mmh3                                             2.5.1
mock                                             4.0.2
more-itertools                                   8.4.0
mpld3                                            0.5.1
mpmath                                           1.0.0
msgpack                                          1.0.0
msrest                                           0.6.18
multidict                                        4.7.6
multipledispatch                                 0.6.0
multiprocess                                     0.70.10
murmurhash                                       1.0.2
nbconvert                                        5.4.0
nbdime                                           2.0.0
nbformat                                         4.4.0
nbresuse                                         0.3.1
nltk                                             3.4.1
nose                                             1.3.7
notebook                                         6.0.3
notification-center                              0.0.0
nteract-on-jupyter                               2.0.7
nteract-scrapbook                                0.2.0
numba                                            0.49.1
numpy                                            1.19.1
oauth2client                                     4.1.3
oauthenticator                                   0.8.0
oauthlib                                         2.1.0
opt-einsum                                       3.3.0
osqp                                             0.6.1
packaging                                        18.0
pamela                                           0.3.0
pandas                                           0.24.2
pandocfilters                                    1.4.2
papermill                                        0.15.0
parse                                            1.16.0
parse-type                                       0.5.2
parso                                            0.3.1
partd                                            1.1.0
pastel                                           0.2.0
pathspec                                         0.8.0
patsy                                            0.5.0
perspective-dash-component                       0.0.7
perspective-python                               0.1.11
pexpect                                          4.6.0
pickleshare                                      0.7.5
Pillow                                           7.2.0
pip                                              20.2.2
pixiedust                                        1.1.14
pkginfo                                          1.5.0.1
plac                                             1.1.3
plotly                                           4.5.3
plotly-express                                   0.4.1
pluggy                                           0.13.1
poetry                                           1.0.9
pprofile                                         2.0.5
preshed                                          3.0.2
prometheus-client                                0.3.1
prompt-toolkit                                   2.0.9
protobuf                                         3.8.0
psutil                                           5.7.2
psycopg2-binary                                  2.7.5
ptyprocess                                       0.6.0
py                                               1.9.0
py-heat                                          0.0.6
py-heat-magic                                    0.0.2
py4j                                             0.10.7
pyarrow                                          0.14.1
pyasn1                                           0.4.4
pyasn1-modules                                   0.2.2
pybuilder                                        0.12.6
pycodestyle                                      2.6.0
pycosat                                          0.6.3
pycparser                                        2.19
pycryptodomex                                    3.9.8
pycurl                                           7.43.0.2
pyflakes                                         2.2.0
PyGithub                                         1.43.7
Pygments                                         2.2.0
pygobject                                        3.26.1
PyHamcrest                                       1.9.0
PyJWT                                            1.6.4
pylev                                            1.3.0
pymc3                                            3.5
PyMeeus                                          0.3.7
pyOpenSSL                                        18.0.0
pyparsing                                        2.2.1
pyrsistent                                       0.14.5
PySocks                                          1.6.8
pyspark                                          2.4.5
pyspark-stubs                                    2.4.0.post1
pystan                                           2.19.0.0
pytest                                           5.0.1
python-apt                                       1.6.5+ubuntu0.3
python-dateutil                                  2.7.3
python-editor                                    1.0.3
python-oauth2                                    1.1.0
python-pptx                                      0.6.18
python-snappy                                    0.5.4
pythreejs                                        2.1.1
pytz                                             2018.5
PyYAML                                           3.13
pyzmq                                            17.1.2
qtconsole                                        4.4.1
realtimeprotobuf                                 3.6.89
regex                                            2020.7.14
requests                                         2.24.0
requests-futures                                 0.9.7
requests-oauthlib                                1.0.0
requests-toolbelt                                0.9.1
retrying                                         1.3.3
rsa                                              4.0
ruamel.yaml                                      0.15.71
s3fs                                             0.3.5
s3transfer                                       0.2.1
scikit-learn                                     0.23.2
scipy                                            1.5.2
scs                                              2.1.2
seaborn                                          0.8.1
SecretStorage                                    3.1.2
Send2Trash                                       1.5.0
service-identity                                 17.0.0
setuptools                                       39.0.0
setuptools-git                                   1.2
shellingham                                      1.3.2
simpervisor                                      0.3
simple-salesforce                                0.74.2
simplegeneric                                    0.8.1
six                                              1.12.0
slacker                                          0.13.0
smart-open                                       2.1.0
smmap                                            3.0.4
snowflake-connector-python                       1.7.10
snowflake-sqlalchemy                             1.1.14
sortedcontainers                                 2.2.2
soupsieve                                        2.0.1
spacy                                            2.2.2
sparkhub                                         1.1.100
sparkmeasure                                     0.13.4
SQLAlchemy                                       1.2.12
sqlparse                                         0.2.4
srsly                                            1.0.2
ssh-import-id                                    5.7
statsmodels                                      0.10.0
sympy                                            1.3
tabulate                                         0.8.7
tblib                                            1.7.0
tensorboard                                      2.1.1
tensorflow                                       2.1.0
tensorflow-estimator                             2.1.0
tensorflow-gpu                                   2.1.0
termcolor                                        1.1.0
terminado                                        0.8.1
testfixtures                                     6.14.1
testpath                                         0.4.1
textwrap3                                        0.9.1
Theano                                           1.0.3
thinc                                            7.3.1
thirdparty-protoc-gen-validate                   0.3.0
threadpoolctl                                    2.1.0
tinys3                                           0.1.12
toml                                             0.10.1
tomlkit                                          0.5.11
toolz                                            0.9.0
torch                                            1.4.0
torchtext                                        0.2.3
tornado                                          5.1.1
tqdm                                             4.26.0
traitlets                                        4.3.2
traittypes                                       0.2.1
Twisted                                          18.7.0
typed-ast                                        1.4.1
typing                                           3.7.4.3
typing-extensions                                3.7.4.3
tzlocal                                          2.1
ua-parser                                        0.8.0
unattended-upgrades                              0.1
uritemplate                                      3.0.1
urllib3                                          1.23
vdom                                             0.5
vega-datasets                                    0.5.0
wasabi                                           0.7.1
wcwidth                                          0.1.7
webencodings                                     0.5.1
websocket-client                                 0.53.0
Werkzeug                                         0.14.1
wheel                                            0.35.1
widgetsnbextension                               3.5.1
wordcloud                                        1.8.0
wrapt                                            1.12.1
xarray                                           0.10.9
xgboost                                          0.90
XlsxWriter                                       1.3.3
xlwt                                             1.3.0
yapf                                             0.24.0
yarl                                             1.5.1
zict                                             2.0.0
zipp                                             3.1.0
zope.interface                                   4.7.2

**Comment by TomAugspurger** [comment]
What happens if you update setuptools to something newer (50.0.0 is the latest)?

**Comment by gitclem** [comment]
Investigating further....  this is some weirdness with Jupyter Lab (JL) (and perhaps my company's installation of JL...)

If I launch JL, open a terminal, pip install as above, start python inside the terminal, then I can import dask and dask_ml without any problems.

BUT if I then go to a JL page and try to import, I get errors.

But, today, the errors are weirdly different...  I'm going to ping my company's help and see if they can figure this out....

(Pip install upgrade of setuptools doesn't help.)

```
---> 47 import dask_ml
     48 
     49 # %%

/usr/local/lib/python3.7/dist-packages/dask_ml/__init__.py in <module>
      2 
      3 # Ensure we always register tokenizers
----> 4 from dask_ml.model_selection import _normalize
      5 
      6 __all__ = []

/usr/local/lib/python3.7/dist-packages/dask_ml/model_selection/__init__.py in <module>
      4 on the underlying estimators being used.
      5 """
----> 6 from ._hyperband import HyperbandSearchCV
      7 from ._incremental import IncrementalSearchCV, InverseDecaySearchCV
      8 from ._search import GridSearchCV, RandomizedSearchCV, check_cv, compute_n_splits

/usr/local/lib/python3.7/dist-packages/dask_ml/model_selection/_hyperband.py in <module>
     10 from sklearn.utils import check_random_state
     11 
---> 12 from ._incremental import BaseIncrementalSearchCV
     13 from ._successive_halving import SuccessiveHalvingSearchCV
     14 

/usr/local/lib/python3.7/dist-packages/dask_ml/model_selection/_incremental.py in <module>
     12 
     13 import dask
---> 14 import dask.array as da
     15 import dask.dataframe as dd
     16 import numpy as np

ModuleNotFoundError: No module named 'dask.array'; 'dask' is not a package

```

and 

```
----> 1 import dask_ml

/usr/local/lib/python3.7/dist-packages/dask_ml/__init__.py in <module>
      2 
      3 # Ensure we always register tokenizers
----> 4 from dask_ml.model_selection import _normalize
      5 
      6 __all__ = []

/usr/local/lib/python3.7/dist-packages/dask_ml/model_selection/__init__.py in <module>
      4 on the underlying estimators being used.
      5 """
----> 6 from ._hyperband import HyperbandSearchCV
      7 from ._incremental import IncrementalSearchCV, InverseDecaySearchCV
      8 from ._search import GridSearchCV, RandomizedSearchCV, check_cv, compute_n_splits

/usr/local/lib/python3.7/dist-packages/dask_ml/model_selection/_hyperband.py in <module>
     10 from sklearn.utils import check_random_state
     11 
---> 12 from ._incremental import BaseIncrementalSearchCV
     13 from ._successive_halving import SuccessiveHalvingSearchCV
     14 

/usr/local/lib/python3.7/dist-packages/dask_ml/model_selection/_incremental.py in <module>
     11 from warnings import warn
     12 
---> 13 import dask
     14 import dask.array as da
     15 import dask.dataframe as dd

/efs/notebooks/home/clem.wang/INFERENCE-viewability-training/dask.py in <module>
     57 
     58 # %%
---> 59 import dask.array
     60 
     61 # %%

ModuleNotFoundError: No module named 'dask.array'; 'dask' is not a package
```

**Comment by mrocklin** [comment]
I suspect that you have a file named dask.py in your local directory

**Comment by gitclem** [comment]
> I suspect that you have a file named dask.py in your local directory

You're right!

I'm now going to check up on the setuptools version.

**Comment by gitclem** [comment]
> What happens if you update setuptools to something newer (50.0.0 is the latest)?

The problem goes away with setuptools-50.0.2 !  Thanks!
