### ISSUE TITLE
TFIDF vectorizer

### ISSUE THREAD

**Issue by dfernan** [dask/dask-ml#744]
I'd want to be able to do TF-IDF calculations in Dask in a similar fashion as in apache spark. https://spark.apache.org/docs/latest/mllib-feature-extraction.html

Right now, counting/hashing vectorizer are similar and it does exist. They’re in Dask-ML and are the same as TFIDF without the normalization/function.

Another implementation exists in rapids/cuml, but not sure how easy it'd be to translate it to the Dask framework.
https://github.com/rapidsai/cuml/blob/cdb14e7de6a40d8d707d29b2889a89aa553125ee/python/cuml/feature_extraction/_tfidf_vectorizer.py.

**Comment by TomAugspurger** [comment]
Thanks. We have https://github.com/dask/dask-ml/issues/5 for this already. Let us know if you're interested in working on it.

**Comment by stsievert** [comment]
@dfernan I also point to the cuml implementation in https://github.com/dask/dask-ml/issues/5#issuecomment-698427819, which explicitly supports Dask.
