### ISSUE TITLE
Change fitted values to be concrete

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-ml#75]
See https://github.com/dask/dask-ml/issues/6#issuecomment-331915143 for more. I think the eventual goal is to have a `compute` keyword in each estimators `__init__` method that defaults to True.

Need to update `MinMaxScaler` and `StandardScaler`.

**Comment by muammar** [comment]
I know this is old, but have you considering adding an option where one can choose `persist` over `compute`?.

**Comment by TomAugspurger** [comment]
I've not. Are you primarily interested in the non-blocking behavior of
persist?

**Comment by muammar** [comment]
The thing is that I have a use case where I preprocess some features, and then I need to restructure them. That means that I compute them, then they are returned to memory by `.compute` and memory consumption is too high. What I wanted was to have the preprocess features as futures and create the dict from there. Does that make sense?

**Comment by TomAugspurger** [comment]
Your dataset is wide enough that the a size (n_features,) array doesn’t fit in memory?
