### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-ml#752]
Due to changes in the Travis CI billing, the Dask org is migrating CI to GitHub Actions.

This repo contains a `.travis.yml` file which needs to be replaced with an equivalent `.github/workflows/ci.yml` file.

See dask/community#107 for more details.

**Comment by jameslamb** [comment]
Could I take this? I've done a lot of GitHub Actions stuff, would be happy to help.

**Comment by TomAugspurger** [comment]
That’d be great, though I may be slow to review for the next week or two.

**Comment by jameslamb** [comment]
ok thanks!

**Comment by jameslamb** [comment]
I started on this tonight and realized two things:

* `dask-ml` only uses Travis to build and publish docs, with `doctr`
* `doctr` is tightly coupled to Travis: https://github.com/drdoctr/doctr

It looks like there is some discussion about supporting other CI providers (https://github.com/drdoctr/doctr/issues/351), but right now that's just a discussion.

So I think this is something that needs to be handled maintainers here, and that the choices are:

* do nothing with this repo and wait for `doctr` to add GitHub Actions Support (and/or help them do that)
* switch to readthedocs like other Dask projects:
    - `dask/dask`: https://readthedocs.org/projects/dask/builds/
    - `dask/dask-cloudprovider`: https://readthedocs.org/projects/dask-cloudprovider/builds/

**Comment by jrbourbeau** [comment]
Alternatively, some other repos in the Dask org are switching to using GitHub actions to build and deploy their docs. For example, here's what the relevant workflow for dask-tutorial looks like: https://github.com/dask/dask-tutorial/blob/master/.github/workflows/ci-build.yaml

**Comment by jameslamb** [comment]
Makes sense. Either way, just to be clear I think I should step away from this issue.

Setting up different integrations for pushing docs should be done by maintainers, since it will require things I don't have permission to do, like logging in to other services (like readthedocs) or changing repo settings (for GitHub pages).

**Comment by mmccarty** [comment]
Can this issue be closed with #754 or is there further work here?

**Comment by TomAugspurger** [comment]
Might be some further work if we wanted to move all of the jobs to GitHub actions. Right now it’s just the docs.

**Comment by mmccarty** [comment]
That's what I was wondering. I can take a stab at it, if GH actions are desired.

**Comment by jrbourbeau** [comment]
Closing as it looks like tests and code linting were moved over to GitHub actions in https://github.com/dask/dask-ml/pull/863 (thanks @TomAugspurger). Feel free to let me know if I'm missing something and we can re-open as needed
