### ISSUE TITLE
Naive bayes

### ISSUE THREAD

**Issue by rikturr** [dask/dask-ml#759]
Hello! I noticed that there is a `dask_ml.naive_bayes.GaussianNB` class, but doesn't seem to be a mention of it in the docs. I tried fitting and predicting with some example data and it seems to work. Is the implementation not yet ready, or does it just need to be added to the docs? I am happy to add docs entry if its the latter.

This came up while I was working on #386, ~~because it looks like `GaussianNB` also returns a 1-d array rather than an array of shape (N, 2)~~. _Correction_: `GaussianNB` actually does return an array of shape (N, 2).

**Comment by jrbourbeau** [comment]
I think this is just an oversight in the docs (though @TomAugspurger can correct me if that's not that case). A documentation PR would be welcome @rikturr

**Comment by TomAugspurger** [comment]
Yeah probably a doc issue.
