### ISSUE TITLE
dask_ml.cluster raises ImportError for `_k_init`

### ISSUE THREAD

**Issue by abduhbm** [dask/dask-ml#768]
**What happened**:
Importing `dask_ml.cluster` raises ImportError for `_k_init` from `sklearn.cluster._kmeans`.

**What you expected to happen**:
no complaints upon importing.

**Minimal Complete Verifiable Example**:

```
import dask_ml.cluster
Traceback (most recent call last):
...
~/workplaces/.venv/lib/python3.7/site-packages/dask_ml/cluster/_compat.py in <module>
----> 1 from sklearn.cluster._kmeans import _k_init
      2 
      3 __all__ = ["_k_init"]

ImportError: cannot import name '_k_init' from 'sklearn.cluster._kmeans' (~/workplaces/.venv/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py)
```

**Anything else we need to know?**:
This happens with Scikit-learn version: 0.24.0

**Environment**:

- Dask version: 2020.12.0
- Python version: Python 3.7.6
- Operating System: MacOS
- Install method (conda, pip, source): pip

**Comment by bidhya** [comment]
I updated to scikit-learn 0.24.1 and still get the same import error

**Comment by abduhbm** [comment]
@bidhya which dask_ml version you are using?

**Comment by abduhbm** [comment]
@bidhya the fix in PR #769 was merged to master branch but not in a release yet.

**Comment by bidhya** [comment]
Thanks @abduhbm . I will wait for the release then

**Comment by bidhya** [comment]
So for release, are we looking for weeks or months?

**Comment by TomAugspurger** [comment]
Once a maintainer has time. Not sure when that will be.

I believe that CI is failing right now. If you have time, it'd be helpful to get that passing to ensure it's safe to release.
