### ISSUE TITLE
ValueError: Mismatched divisions. 

### ISSUE THREAD

**Issue by mi4da** [dask/dask-ml#775]
**What happened**: when i used the dask_ml.model_selection.train_test_split that want random split the dask-dataframe to training my model, Error come.

**What you expected to happen**: i want  dask_ml.model_selection.train_test_split  can give me split datas

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
import xgboost as xgb
from dask import dataframe as dd
from dask_ml.model_selection import train_test_split
# read data
X = dd.read_csv(r"... .txt",sep=' ',header=None)
Y = dd.read_csv(r"... .txt",header=None)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
```
![image](https://user-images.githubusercontent.com/55870943/105636584-da4b9a00-5ea3-11eb-9adc-325ec38ab2e2.png)

**Anything else we need to know?**:this is my data looks like in dask-dataframe:
and X.shape : (836075,128);Y.shape:(836075,1),there are also no null-value,i checked it.
![image](https://user-images.githubusercontent.com/55870943/105636629-fbac8600-5ea3-11eb-8612-0c26d568a3ce.png)

**Environment**:

- Dask version: 2.30.0
- Dask_ml version: 1.7.0
- Python version: 3.6
- Operating System: win10
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
Looks like the `.divisions` don't match between X and `y`. I think you can use `.repartition`

**Comment by TomAugspurger** [comment]
Let me know if that wasn't the issue.
