### ISSUE TITLE
the binder URL should be changed from master to main

### ISSUE THREAD

**Issue by murphyk** [dask/dask-ml#790]
The widget at the top of this page
https://ml.dask.org/
points to 
https://mybinder.org/v2/gh/dask/dask-examples/master?filepath=machine-learning.ipynb
but should point to
https://mybinder.org/v2/gh/dask/dask-examples/main?filepath=machine-learning.ipynb

**Comment by jrbourbeau** [comment]
Thanks for pointing this out @murphyk. This should be fixed by https://github.com/dask/dask-ml/pull/792
