### ISSUE TITLE
ML-dask binder example uses to-be-deprecated iid flag in GridSearchCV 

### ISSUE THREAD

**Issue by murphyk** [dask/dask-ml#791]
Cell 4 of
https://hub.gke2.mybinder.org/user/dask-dask-examples-9f3o81ph/notebooks/machine-learning.ipynb
contains this code fragment
```
grid_search = GridSearchCV(SVC(gamma='auto', random_state=0, probability=True),
                           param_grid=param_grid,
                           return_train_score=False,
                           iid=True,
                           cv=3,
                           n_jobs=-1)
```
This produces the following warning
```
srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/model_selection/_search.py:847: FutureWarning: The parameter 'iid' is deprecated in 0.22 and will be removed in 0.24.
```
Context:
https://github.com/scikit-learn/scikit-learn/pull/9103

**Comment by jrbourbeau** [comment]
Thanks for reporting @murphyk! It looks like the current and future behavior is equivalent to `iid=True`, so it should be okay to just drop the `iid` keyword altogether in this notebook. Are you interested in submitting a PR? (no obligation though)

**Comment by hristog** [comment]
Hi @jrbourbeau, I've raised https://github.com/dask/dask-examples/pull/185 to address this.
Please, let me know if it should've been raised in a different repository instead.

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask-examples/pull/185
