### ISSUE TITLE
ImportError: Cannot import `StratifiedKFold` from `dask_ml.model_selection`

### ISSUE THREAD

**Issue by hsteinshiromoto** [dask/dask-ml#810]
Hi

I am trying to import `StratifiedKFold` from `dask_ml.model_selection`
**What happened**:

I get the error:
```
ImportError: Cannot import StratifiedKFold from dask_ml.model_selection
```

**What you expected to happen**:
Do not show error.

**Minimal Complete Verifiable Example**:
```python
>>> from dask_ml.model_selection import StratifiedKFold
ImportError: Cannot import StratifiedKFold from dask_ml.model_selection
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 1.8.0
- Python version: 3.9.2
- Operating System: WSL (Windows)
- Install method (conda, pip, source): `pip3 install "dask[complete]" dask-ml[complete]`

**Comment by hristog** [comment]
Hi @hsteinshiromoto,

As per https://github.com/dask/dask-ml/blob/main/dask_ml/model_selection/__init__.py#L9, `StratifiedKFold` is not currently supported.

There is some related discussion in #535.

**Comment by hristog** [comment]
This issue could probably be closed, unless the maintainers believe it should be re-phrased as a feature request.
