### ISSUE TITLE
Codecov settings don't take the `main` branch into account

### ISSUE THREAD

**Issue by hristog** [dask/dask-ml#817]
**What happened**: According to Codecov, a `master` branch [exists](https://app.codecov.io/gh/dask/dask-ml/branch/master), but a `main` branch [doesn't](https://app.codecov.io/gh/dask/dask-ml/branch/main).
This could probably be configured via updating the [Codecov settings](https://app.codecov.io/gh/dask/dask-ml/settings) (requires maintainer access).

**What you expected to happen**: Codecov settings to take the `main` branch into account.

**Minimal Complete Verifiable Example**: N/A

**Anything else we need to know?**: N/A

**Environment**: N/A

**Comment by jrbourbeau** [comment]
Thanks @hristog -- I've updated the default branch on codecov to be `main`
