### ISSUE TITLE
Version 1.9.0 of PyPI is missing a tag and changelog

### ISSUE THREAD

**Issue by bsipocz** [dask/dask-ml#846]
The most recent version on PyPI is v1.9.0, uploaded in early May. However I don't see any tags for this in the repo, neither commits around that date. It is missing from the changelog, too.

**Comment by jrbourbeau** [comment]
Good catch, thanks @bsipocz! cc @TomAugspurger who I suspect did that release

**Comment by TomAugspurger** [comment]
Sorry about that. Not sure what happened, since we don't have automated releases set up for this repo. https://github.com/dask/dask-ml/releases/tag/v1.9.0 is present now and the changelog update is at https://github.com/dask/dask-ml/pull/847.

**Comment by bsipocz** [comment]
Thank you very much for the quick fix!
