### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-ml#884]
The 2021.11.0 release of `dask` recently broke some functionality in `dask-ml` which has since been fixed (xref https://github.com/dask/dask-ml/pull/878). It's probably worth pushing out a `dask-ml` release which includes that patch. What do others think? FWIW I'm happy to handle releasing if @TomAugspurger is busy with other things (Tom, does `dask-ml` use the usual [`dask/dask` release process](https://github.com/dask/dask/blob/main/docs/release-procedure.md), or are there additional / different steps?)

There's also https://github.com/dask/dask-ml/pull/862 which has been active recently and looks like it's close to being completed. Should we wait for that before releasing?

**Comment by TomAugspurger** [comment]
I think #862 is close. I think it's worth waiting a day or two to get that in.

My last round of CI changes updated the release stuff. Aside from a changelog, a Dask-ML release should just require making a [release on GitHub](https://github.com/dask/dask-ml/releases/new). Then the [release](https://github.com/dask/dask-ml/blob/main/.github/workflows/release.yaml) action takes care of building a wheel and sdist and uploading it to PyPI (might be worth trying that for dask/dask or dask/distributed, if you want to avoid having to tag / build wheels locally).

**Comment by TomAugspurger** [comment]
dask-ml 2021.11.16 is released to PyPI with https://github.com/dask/dask-ml/releases/tag/v2021.11.16 is released to PyPI. Thanks James!
