### ISSUE TITLE
Test failures with latest dask from main

### ISSUE THREAD

**Issue by ayushdg** [dask/dask-ml#895]
**What happened**:
Multiple test failures post the merge of dask/dask@fa15d0c6d9604ca2267290942317058735a73d78 with `ValueError` around HLG graph layer names. 

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

here's the output from one of the tests, most errors I saw were of a similar nature. 

`test_incremental_sparse_inputs`
```python
E  ValueError: Layer ('fit-a42744f10f719e4c75eaf92f1c890e5f', 2) not in the HighLevelGraph's layers: 
['fit-a42744f10f719e4c75eaf92f1c890e5f', 'array-873f3177c716dd9595aeb50eb00dcb2b', 'array-fab8aba9efacb871881c861cdab60e29']
```

**Anything else we need to know?**:
Initially popped up as part of failing tests in dask-contrib/dask-sql#350
**Environment**:

- Dask version: 2021.12.0+13.gfa15d0c6 or newer
- Python version: 3.8
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): pip

**Comment by ayushdg** [comment]
Looking through the test failures, explicitly passing the layer name here: https://github.com/dask/dask-ml/blob/8cb4c2f79a058c82e360774e0fad89797361f1f3/dask_ml/_partial.py#L128 should fix the errors when using newer versions of dask.

**Comment by ayushdg** [comment]
Happy to open a pr for this but wanted to confirm with the maintainers first, perhaps @jrbourbeau or @TomAugspurger have some insight as to why the upstream CI jobs didn't report anything.

**Comment by jrbourbeau** [comment]
Thanks for reporting @ayushdg. There's already an issue for upstream CI failures at https://github.com/dask/dask-ml/issues/894. The logs in that issue to be updated to include the `test_incremental_sparse_inputs` traceback here, but tests aren't running for other reasons

**Comment by ayushdg** [comment]
Thanks for clarifying! In that case I'd be happy to open a PR (seems like it's a small fix) to address this
