### ISSUE TITLE
New dask-ml release to resolve upstream breaking changes?

### ISSUE THREAD

**Issue by charlesbluca** [dask/dask-ml#899]
With Dask 2022.01.0 out, the breaking changes discussed in https://github.com/dask/dask-ml/issues/895 are now out in a stable Dask release. These were resolved by @ayushdg in https://github.com/dask/dask-ml/pull/898, but have not yet been published in a stable release.

Would it be possible to do another dask-ml release soon so that these breakages are resolved for downstream libraries? For context, this is impacting dask-sql's CI, which depends on the latest stable dask and dask-ml (example of a failing run):

- https://github.com/dask-contrib/dask-sql/runs/4827398398?check_suite_focus=true

cc @TomAugspurger @jrbourbeau

**Comment by TomAugspurger** [comment]
Yeah, I can do a release now if there's no blockers.

For reference, the release process just requires creating a new [GitHub release](https://github.com/dask/dask-ml/releases) with the desired tag.

**Comment by charlesbluca** [comment]
One thing to consider is the upstream failures coming from https://github.com/scikit-learn/scikit-learn/pull/21880 recorded in https://github.com/dask/dask-ml/issues/894 - it looks like the latest stable release of scikit-learn (1.0.2) doesn't yet have the breaking changes, but its nightlies do. We might want to address this now by either:

- making 1.0.2 the max version for scikit-learn
- adding a special case for `scikit-learn>1.0.2` so that we don't import `_check_param_grid`

Or we could address it later on when this change is in a stable release of sklearn since dask-ml's release process seems pretty simple - currently checking to see if it's possible to make a fix for this now

**Comment by charlesbluca** [comment]
Think we should be able to resolve the breakage with a pretty small change - opened up https://github.com/dask/dask-ml/pull/901 attempting to do this

**Comment by TomAugspurger** [comment]
#901 is merged. Anything else?

**Comment by jrbourbeau** [comment]
All known upstream failures have been resolved (xref https://github.com/dask/dask-ml/pull/902#issuecomment-1017921102), so +1 from me

**Comment by charlesbluca** [comment]
Nothing else needed on dask-sql's end - +1 on releasing

**Comment by charlesbluca** [comment]
Ah I see that the release is out - thanks for the help @TomAugspurger! Will reopen if something else comes up for any reason.
