### ISSUE TITLE
Roll a new release

### ISSUE THREAD

**Issue by aidanheerdegen** [dask/dask-ml#928]
Are there plans for a new release/tag for `conda` users so `dask-ml` installs cleanly with recent versions of `scikit-learn`

https://github.com/dask/dask-ml/issues/908

Thanks

**Comment by TomAugspurger** [comment]
I can click a couple buttons to make a release, but I think https://github.com/dask/dask-ml/pull/921 needs to be reviewed first. Can anyone take a look at that?

**Comment by stsievert** [comment]
I think #914 is ready for merge too. I'd like to see it in the next release.

I think it should be merged if there are no objections (as expressed in https://github.com/dask/dask-ml/pull/914#issuecomment-1133760219).

**Comment by TomAugspurger** [comment]
https://pypi.org/project/dask-ml/2022.5.27/ is up on PyPI. Thanks all for help with the PRs!

**Comment by jakirkham** [comment]
Also on conda-forge: https://github.com/conda-forge/dask-ml-feedstock/pull/34
