### ISSUE TITLE
“python_requires” should be set with “>=3.7”, but dask-ml 2022.5.27 set as ">=3.6".

### ISSUE THREAD

**Issue by PyVCEchecker** [dask/dask-ml#942]
Currently, the keyword argument **python_requires** of **setup()** is set as ">=3.6", but I found it is not compatible with **Python<3.7**. My local Python version is 3.6, and I encounter the following error when executing “pip install dask-ml==2022.5.27”

```
Collecting dask-ml==2022.5.27
  Downloading dask_ml-2022.5.27-py3-none-any.whl (148 kB)
     |████████████████████████████████| 148 kB 544 kB/s 
Collecting scipy
  Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 134 kB/s 
Collecting multipledispatch>=0.4.9
  Downloading multipledispatch-0.6.0-py3-none-any.whl (11 kB)
Collecting numba>=0.51.0
  Downloading numba-0.53.1-cp36-cp36m-manylinux2014_x86_64.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 643 kB/s 
Collecting dask[array,dataframe]>=2.4.0
  Downloading dask-2021.3.0-py3-none-any.whl (925 kB)
     |████████████████████████████████| 925 kB 617 kB/s 
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 566 kB/s 
Collecting dask-glm>=0.2.0
  Downloading dask_glm-0.2.0-py2.py3-none-any.whl (12 kB)
ERROR: Could not find a version that satisfies the requirement scikit-learn>=1.0.0 (from dask-ml) (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2, 0.22.2.post1, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.dev0, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for scikit-learn>=1.0.0

```

Dependencies of this distribution are listed as follows:

```
    "dask[array,dataframe]>=2.4.0",
    "distributed>=2.4.0",
    "numba>=0.51.0",
    "numpy>=1.20.0",
    "pandas>=0.24.2",
    "scikit-learn>=1.0.0",
    "scipy",
    "dask-glm>=0.2.0",
    "multipledispatch>=0.4.9",
    "packaging",
```

I found that **scikit-learn>=1.0.0** requires **Python>=3.7**, which results in installation failure of dask-ml in Python3.6.

Way to fix:
modify **setup()** in **setup.py**, amend **python_requires** keyword argument
```
setup(…
     python_requires='>=3.7'
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by jrbourbeau** [comment]
Thanks @PyVCEchecker -- see https://github.com/dask/dask-ml/pull/944 which updates `python_requires`

**Comment by TomAugspurger** [comment]
Just for my own understanding: what will happen once #944 is merged? I suspect it'll be exactly the same right, since pip will skip our next release?

In theory, if we had bumped our python_requires when we bumped our scikit-learn then pip would have kept going backwords until it found a version of dask-ml that supported our pyhton_requires (likewise for our dependencies)?

**Comment by PyVCEchecker** [comment]
Yes, the result of _pip install dask-ml_ is unchanged after merging #944 , but pypi shows an error message, where users using python3.6 mistakenly think they can install the latest desk-ml when in fact they can't. Not fixing is OK, fixing is better, right?
