### ISSUE TITLE
Issue with dask_ml

### ISSUE THREAD

**Issue by mad-stat** [dask/dask-ml#943]
I am facing this issue every time I tend to use dask for my ML project. Even I tried to follow the XGBoost.ipynb file of the dask-examples repository but this error crops up whenever I am trying to import stuffs from dask_ml

cannot import name '_is_constant_feature' from 'sklearn.preprocessing._data' (/opt/conda/lib/python3.7/site-packages/sklearn/preprocessing/_data.py)

**Comment by jacobtomlinson** [comment]
Closing as duplicate of #893
