### ISSUE TITLE
Add versions after 2023.3.24 to the Anaconda main channel

### ISSUE THREAD

**Issue by xlt208** [dask/dask-ml#995]
Hello! We are looking to upgrade `dask-ml` to a recent version where Python 3.11.9 is supported. We discovered that the newer versions are only hosted on the `conda-forge` channel but not the main or the mirroring channel: 

- https://anaconda.org/conda-forge/dask-ml 
  - latest version: **2024.4.4**
- https://anaconda.org/main/dask-ml 
  - latest version: **2023.3.24**
- https://anaconda.org/anaconda/dask-ml 
  - latest version: **2023.3.24**

For security reasons mentioned in the blog below, we prefer not to install packages from `conda-forge`.  
- https://conda-forge.org/blog/2023/03/12/circle-ci-security-breach/

Would you please consider adding the versions after 2023.3.24 to the other two channels as well? 

Thank you!

**Comment by jrbourbeau** [comment]
Thanks for the issue @xlt208. The conda main channel is maintained by folks at Anaconda, not the Dask community. @martindurant do you know the right person or team who would want to know about this?

**Comment by jrbourbeau** [comment]
Thanks @martindurant! 

Closing as there's nothing left to do here at the moment. We can reopen as needed.
